cemu-project/Cemu

BUILD.md
Very tiny update here to avoid potential confusion.
Also updated the path to the generated solution for consistency.
=> Update BUILD.md to reference correct solution generation bat file path

src/Cafe/IOSU/PDM/iosu_pdm.cpp
With PR #52 this path was missed
=> fix unix path on IOSU/PDM

src/Cafe/HW/Latte/Core/LatteOverlay.cpp, src/Cafe/OS/libs/nn_acp/nn_acp.cpp, src/Cemu/Tools/DownloadManager/DownloadManager.cpp, src/gui/MemorySearcherTool.cpp, src/gui/windows/PPCThreadsViewer/DebugPPCThreadsWindow.cpp, src/util/Zir/Core/IR.cpp
use the definition in cinttypes for portability
=> fix some printf format specifiers

dist/linux/info.cemu.Cemu.desktop, dist/linux/info.cemu.Cemu.metainfo.xml
Some translation work for the Linux shortcuts to Dutch, designated by "nl".
=> Dutch translations for Linux distributions

src/gui/MainWindow.cpp
https://github.com/cemu-project/Cemu/issues/123
=> Linux cursor hide.

src/Common/betype.h, src/config/ConfigValue.h
Most of the codebase already does this
(Was part of #112)
=> style: use std::enable_if & co instead of boost::

src/gui/ChecksumTool.cpp, src/gui/MainWindow.cpp, src/gui/TitleManager.cpp, src/gui/components/wxGameList.cpp, src/gui/components/wxTitleManagerList.cpp
Replaced every instance of ShellExecute with wxLaunchDefaultBrowser
=> Portable way of opening URLs and directories

dist/linux/info.cemu.Cemu.metainfo.xml
Very minor changes, just trying to get it as close to the original english wording as possible.
=> Slight tweaks to greek translation

src/Cafe/HW/Espresso/PPCTimer.cpp
#188 broke it so here's the fix
=> fix clang-cl build

src/gui/components/wxGameList.cpp
Refactored to pre-calculate the row colors at the beginning of the function. If the background color is almost white as it is on Windows, we'll use the previous bluish secondary color instead of grey-scale lightness adjustment.
=> Refactor wxGameList color code and match previous style on light theme

BUILD.md
=> [docs] [BUILD.md] Explain how to update local cemu repo + General fixes

src/gui/MemorySearcherTool.cpp, src/gui/components/wxLogCtrl.cpp, src/gui/components/wxTitleManagerList.cpp
this fixes the last remaining issue when building on macOS using clang 14
=> fixed the string encoding issue on macOS

BUILD.md
See https://github.com/cemu-project/Cemu/pull/287
=> Remove -DPUBLIC_RELEASE=ON from macOS command

src/Cafe/HW/Latte/Renderer/OpenGL/OpenGLRendererCore.cpp
=> Use correct Texture clear in LatteDraw_handleSpecialState8_clearAsDepth

dependencies/ih264d/CMakeLists.txt, dependencies/ih264d/common/x86/ih264_chroma_intra_pred_filters_ssse3.c, dependencies/ih264d/common/x86/ih264_deblk_chroma_ssse3.c, dependencies/ih264d/common/x86/ih264_deblk_luma_ssse3.c, dependencies/ih264d/common/x86/ih264_ihadamard_scaling_sse42.c, dependencies/ih264d/common/x86/ih264_ihadamard_scaling_ssse3.c, dependencies/ih264d/common/x86/ih264_inter_pred_filters_ssse3.c, dependencies/ih264d/common/x86/ih264_iquant_itrans_recon_dc_ssse3.c, dependencies/ih264d/common/x86/ih264_iquant_itrans_recon_sse42.c, dependencies/ih264d/common/x86/ih264_iquant_itrans_recon_ssse3.c, dependencies/ih264d/common/x86/ih264_luma_intra_pred_filters_ssse3.c, dependencies/ih264d/common/x86/ih264_mem_fns_ssse3.c, dependencies/ih264d/common/x86/ih264_padding_ssse3.c, dependencies/ih264d/common/x86/ih264_resi_trans_quant_sse42.c, dependencies/ih264d/common/x86/ih264_weighted_pred_sse42.c, dependencies/ih264d/decoder/x86/ih264d_function_selector_sse42.c, dependencies/ih264d/decoder/x86/ih264d_function_selector_ssse3.c
=> ih264 per-function target attribute on clang and GCC

src/Cafe/HW/Espresso/Debugger/DebugSymbolStorage.h, src/Cafe/HW/Espresso/PPCTimer.cpp, src/Cafe/HW/Espresso/Recompiler/PPCRecompiler.cpp, src/Cafe/HW/Latte/Core/FetchShader.cpp, src/Cafe/HW/Latte/Core/LatteBufferCache.cpp, src/Cafe/HW/Latte/Renderer/Vulkan/CachedFBOVk.h, src/Cafe/HW/Latte/Renderer/Vulkan/RendererShaderVk.h, src/Cafe/HW/Latte/Renderer/Vulkan/VulkanPipelineStableCache.cpp, src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp, src/Cafe/IOSU/kernel/iosu_kernel.cpp, src/Cafe/OS/libs/coreinit/coreinit_Callbacks.cpp, src/Cafe/OS/libs/coreinit/coreinit_MPQueue.cpp, src/Cafe/OS/libs/coreinit/coreinit_Synchronization.cpp, src/Cafe/OS/libs/snd_core/ax_ist.cpp, src/Cafe/OS/libs/snd_core/ax_voice.cpp, src/gui/guiWrapper.h, src/gui/input/InputSettings2.cpp, src/gui/input/panels/InputPanel.cpp, src/input/api/Controller.cpp, src/input/api/ControllerState.h, src/input/api/DSU/DSUController.cpp, src/input/api/DirectInput/DirectInputController.cpp, src/input/api/Keyboard/KeyboardController.cpp, src/input/api/SDL/SDLController.cpp, src/input/api/Wiimote/NativeWiimoteController.cpp, src/input/api/XInput/XInputController.cpp, src/input/emulated/EmulatedController.cpp, src/util/helpers/fspinlock.h
Reworked the code for tracking which buttons are pressed because it wasn't thread-safe and I kept getting crashes
=> Make controller button code thread-safe

src/audio/CubebInputAPI.cpp, src/audio/CubebInputAPI.h, src/gui/GeneralSettings2.cpp
=> CubebInput: Avoid redundant CoInitializeEx

dist/linux/appimage.sh
- include libthai.so.0
- set LC_ALL
=> [APPIMAGE] Update AppImage

src/gui/GameUpdateWindow.cpp
=> Fix checking space using non existing folder

src/Cafe/IOSU/legacy/iosu_boss.cpp
=> Download BOSS files if they are not found

dist/linux/appimage.sh
- Interface languages
- Font cache
- GameProfile
=> [APPIMAGE] Fix resource path

src/gui/input/settings/DefaultControllerSettings.cpp
=> fix SDL controller settings reversed y axis

.github/workflows/build.yml
Add libudev headers for better motion support on supported controllers.
=> [APPIMAGE] Better motion support

.github/workflows/build.yml, BUILD.md
Removes the warning as the dependency was fixed
updates the workflow accordingly.
=> Update to llvm15

src/gui/MainWindow.cpp
Don't hide it when game is launched. Easier access to logs, screenshots etc
=> Always show "Open Cemu folder" menu item

src/Cafe/Filesystem/fscDeviceHostFS.cpp
=> coreinit: Correctly return success code in FSRemove

BUILD.md
Fixes #644.
I also reorganize things a smidge so that all the "step 3" troubleshooting is grouped together.
=> Add note about 'span' not found to BUILD.md

src/gui/components/wxTitleManagerList.cpp, src/gui/components/wxTitleManagerList.h
=> Added location column in Title Manager

src/Cafe/HW/Latte/Core/LatteShaderGL.cpp, src/Cafe/HW/Latte/Renderer/OpenGL/RendererShaderGL.cpp, src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
Replaces direct uses of cafeLog_logLine()
Part of #703
=> switched cafeLog_logLine() with cemuLog_log()

src/gui/MainWindow.cpp
In regard to [this issue](https://github.com/cemu-project/Cemu/issues/716), I added the ability to also enter fullscreen mode with F11.
=> Allow user to enter fullscreen with F11

src/config/CemuConfig.cpp, src/config/CemuConfig.h, src/gui/GeneralSettings2.cpp, src/util/ScreenSaver/ScreenSaver.h
=> Fix disable screensaver workaround

src/gui/PadViewFrame.cpp
Forgot to add this to my [original PR](https://github.com/cemu-project/Cemu/pull/720).
=> add F11 hotkey to gamepad view too

src/Cemu/Logging/CemuLogging.cpp, src/Cemu/Logging/CemuLogging.h, src/Common/CMakeLists.txt, src/Common/ExceptionHandler/ExceptionHandler.cpp, src/Common/ExceptionHandler/ExceptionHandler.h, src/Common/ExceptionHandler/ExceptionHandler_posix.cpp, src/Common/ExceptionHandler/ExceptionHandler_win32.cpp, src/main.cpp
- Stack trace and PowerPC info will be written to log.txt now on Linux/MacOS
- A few smaller tweaks to make the stderr output a bit better
=> Improve crash logging on posix

src/Cemu/Logging/CemuLogging.h
=> Dont format logging calls with only the format string

src/gui/GraphicPacksWindow2.cpp
Attempt to fix #801
may also affect #537
=> GraphicsPackWindow2: Use UTF8

src/Cafe/OS/libs/snd_core/ax_internal.h, src/Cafe/OS/libs/snd_user/snd_user.cpp
Fixes some undefined behavior warnings with gcc.
=> Fix some out of bound array access.

bin/gameProfiles/default/000500001010EB00.ini, bin/gameProfiles/default/000500001010ec00.ini, bin/gameProfiles/default/000500001010ed00.ini
=> MK8 has worked with Multicore Recompiler since 1.17.2

src/Cafe/OS/libs/nlibcurl/nlibcurl.cpp, src/Cafe/OS/libs/nn_olv/nn_olv.cpp, src/Cafe/OS/libs/proc_ui/proc_ui.cpp, src/Cafe/OS/libs/proc_ui/proc_ui.h
- Fixes bugs and now allows MK8 to upload rankings!
=> Fix NEX DataStore uploads (nlibcurl) and stub Miiverse PostApp

src/Cafe/CMakeLists.txt, src/Cafe/CafeSystem.cpp, src/Cafe/HW/Latte/Renderer/OpenGL/OpenGLRenderer.cpp, src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp, src/Cafe/IOSU/legacy/iosu_act.cpp, src/Cafe/OS/libs/coreinit/coreinit_MCP.cpp, src/Cafe/OS/libs/nn_olv/nn_olv.cpp, src/Cafe/OS/libs/nn_olv/nn_olv.h, src/Cafe/OS/libs/nn_olv/nn_olv_Common.h, src/Cafe/OS/libs/nn_olv/nn_olv_InitializeTypes.cpp, src/Cafe/OS/libs/nn_olv/nn_olv_OfflineDB.cpp, src/Cafe/OS/libs/nn_olv/nn_olv_OfflineDB.h, src/Cafe/OS/libs/nn_olv/nn_olv_PostTypes.cpp, src/Cafe/OS/libs/nn_olv/nn_olv_PostTypes.h, src/Cafe/TitleList/AppType.h, src/Cafe/TitleList/TitleInfo.h, src/Cafe/TitleList/TitleList.cpp, src/Common/precompiled.h, src/gui/GameUpdateWindow.cpp, src/gui/components/wxTitleManagerList.cpp, src/gui/components/wxTitleManagerList.h, src/main.cpp
This is mostly regression and crash fixes, some improvements to the WUA conversion dialog and additional work on OLV.
=> Several fixes and improvements

dist/linux/info.cemu.Cemu.metainfo.xml
Compared to other package summaries Cemu sounds clunky:
https://flathub.org/apps/search?q=emulator
I used google for the translations, I can't say they're accurate.
=> Simplify appstream summary description

src/gui/GeneralSettings2.cpp, src/gui/GettingStartedDialog.cpp, src/gui/MainWindow.cpp
=> Disable auto-update checkbox/menu on Linux/macOS

dist/linux/appimage.sh
Adds libstdc++.so.6.0.32 to match the update to clang-15
=> [AppImage] Bundle libstdc++

src/gui/components/wxGameList.cpp
This allows the shortcut creation feature to work with under flatpak.
=> Flatpak: Create shortcuts that launch flatpak

src/audio/CubebAPI.cpp, src/audio/CubebInputAPI.cpp
Tested on Windows
Requires OSX/Linux testing.
If working for all, closes #29 & #1016
=> [Cubeb]Custom Implementation for Default Device selection

src/gui/components/wxGameList.cpp
Also now uses the base title id for the title column
=> Add actions for copying title ID, name, and icon

src/gui/components/wxTitleManagerList.cpp
fixes #648
also fix typo and simplify one line
=> fix crash in title manager when sorting by format

src/gui/MainWindow.cpp
=> Fix crash when setting console language while game is running

src/Cafe/CMakeLists.txt, src/Cafe/OS/common/OSCommon.cpp, src/Cafe/OS/libs/nn_sl/nn_sl.cpp, src/Cafe/OS/libs/nn_sl/nn_sl.h, src/Cemu/Logging/CemuLogging.h
Stub GetDefaultWhiteListAccessor__Q2_2nn2slFv to avoid crash in Wii U Menu when an online account is used
=> nn_sl: Stub GetDefaultWhiteListAccessor__Q2_2nn2slFv

src/input/InputManager.cpp
=> InputManager: Assign profile name correctly on save

src/Cafe/OS/libs/nsyshid/Skylander.cpp, src/Cafe/OS/libs/nsyshid/Skylander.h, src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.cpp, src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.h
Just some tidyups for the Skylander code based on some reviews from initial PR, as well as setting the filestream to 0 before writing in the Save() method
=> nsyshid: Skylander Tidyups

src/Cafe/OS/libs/nsyshid/Backend.h, src/Cafe/OS/libs/nsyshid/BackendLibusb.cpp, src/Cafe/OS/libs/nsyshid/BackendLibusb.h, src/Cafe/OS/libs/nsyshid/BackendWindowsHID.cpp, src/Cafe/OS/libs/nsyshid/BackendWindowsHID.h, src/Cafe/OS/libs/nsyshid/Skylander.cpp, src/Cafe/OS/libs/nsyshid/Skylander.h, src/Cafe/OS/libs/nsyshid/nsyshid.cpp
Round 2 of me attempting to implement the SetProtocol and SetReport methods for libusb. Will need user testing on linux for the Skylanders games, and some testing to confirm I haven't broken anything for Lego Dimensions also.
=> nsyshid: Libusb SetProtocol and SetReport

src/Cafe/IOSU/legacy/iosu_boss.cpp
Special thanks to Exzap in the Discord server for figuring this out!
=> [IOSU/BOSS] Fix BOSS not honoring the proxy_server setting.

src/gui/components/wxGameList.cpp
Should fix https://github.com/cemu-project/Cemu/issues/1341
=> Windows: Save icons to Cemu user data directory

src/CMakeLists.txt
=> macOS: fix absolute path to libusb dylib

src/input/api/DSU/DSUControllerProvider.cpp, src/input/api/DSU/DSUControllerProvider.h
Closes: https://github.com/cemu-project/Cemu/issues/1451
=> Boost: Fix building against Boost 1.87.0

src/input/api/Wiimote/l2cap/L2CapWiimote.cpp, src/input/api/Wiimote/l2cap/L2CapWiimote.h
I didn't correctly understand the purpose of each of the sockets, and the code just happened to work because I unintentionally used the correct one for communications.
=> Wiimote/L2CAP: More accurate descriptions for descriptors

dist/linux/info.cemu.Cemu.desktop
hello! 🙂
Gnome dash (and probably some other DE dash) shows generic icon if .desktop doesn't have StartupWMClass=Cemu
so if you can merge this its cool 👍
=> Update info.cemu.Cemu.desktop StartupWMClass=Cemu

src/Cafe/CMakeLists.txt, src/Cafe/OS/libs/nsyshid/Backend.h, src/Cafe/OS/libs/nsyshid/BackendEmulated.cpp, src/Cafe/OS/libs/nsyshid/SkylanderXbox360.cpp, src/Cafe/OS/libs/nsyshid/SkylanderXbox360.h, src/Cafe/OS/libs/nsyshid/Whitelist.cpp, src/Cafe/OS/libs/nsyshid/g721/g721.cpp, src/Cafe/OS/libs/nsyshid/g721/g721.h, src/Cafe/OS/libs/nsyshid/nsyshid.cpp
Skylander Xbox 360 portals are quite different, so I added compatibility for them.
This was possible because of @sanjay900 help and his project https://github.com/sanjay900/portal_of_flipper/
g721.h and g721.cpp, are from [portal_of_flipper](https://github.com/sanjay900/portal_of_flipper/blob/main/audio/g721.c)
=> nsyshid: Add Skylander Xbox 360 Portal support

src/gui/MainWindow.cpp, src/gui/MemorySearcherTool.cpp, src/gui/debugger/BreakpointWindow.cpp, src/gui/debugger/ModuleWindow.cpp, src/gui/debugger/SymbolCtrl.cpp, src/gui/windows/PPCThreadsViewer/DebugPPCThreadsWindow.cpp, src/gui/wxcomponents/checkedlistctrl.h
Use wxID_ANY and wxNOT_FOUND instead of -1.
This is just a trivial cleanup.
=> wxWidgets: cleanup

src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.cpp, src/gui/TitleManager.cpp, src/gui/components/wxTitleManagerList.cpp, src/gui/debugger/DisasmCtrl.cpp, src/gui/debugger/DumpCtrl.cpp, src/gui/debugger/RegisterCtrl.cpp, src/gui/debugger/RegisterWindow.cpp
It fixes the problem described here https://wxwidgets.org/help/msgid-literals/.
=> make code compatible wxWidgets 3.3

src/util/helpers/helpers.cpp
This uses the new API introduced in Windows 10 to set the thread name. It has advantages compared to the old method.
=> Windows: use modern API to set thread name

src/Cafe/OS/libs/coreinit/coreinit_Thread.cpp
Enables flush denormals to zero on ARM64 platforms as well.
=> arm: flush denormals to zero
