CMakeLists.txt

Use more consistent formatting in CMakeLists.txt

---

CMakeSettings.json

No need for a variable when it passes nothing, after all. I'm guessing these were created by default by the VS CMake integration, because VS.

Reformat CMakeSettings.json and remove empty variables

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug-report-feature-request.md
.github/ISSUE_TEMPLATE/config.yml

This adds a basic issue template and a Patreon link to the repository.
Suggestions for better wording/content are very welcome.
The files are loosely based on those of yuzu, but since I wrote a large part of the yuzu ones myself, there should be no licensing issues.

.github: Add issue template and funding information

---

src/Cafe/HW/Latte/Core/LatteShaderCache.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VKRMemoryManager.cpp
src/Cafe/OS/libs/swkbd/swkbd.cpp

This patch fixes the compiler warnings/errors with `format-security` enabled.

Fix ImGui::Text() format strings

---

src/util/helpers/helpers.cpp

The previous implementation used an `std::stringstream` to concatenate the generated random string.
The new one uses a simple preallocated `std::string`, as the size of the output is already known - it is the `length` parameter.
It also uses `std::generate_n()` instead of an explicit loop, making the code more concise and potentially faster, as no calls to `std::string::operator+=` are needed.
Calling `GenerateRandomString(1'000'000)` with the `std::stringstream`-based implementation allocated 16 times, for a total of 3'173'516 bytes. The new one cuts this down to 4 allocs, for a total of 1'076'864 bytes.
Inspired by #64

perf: optimize GenerateRandomString()

---

src/Cemu/napi/napi_helper.cpp
src/config/CemuConfig.cpp
src/config/CemuConfig.h

This will add rudimentary proxy support for napi.
This can be used to manipulate/sniff the packets. (Needs CACERT_NINTENDO_CA_G3.der to be swapped out)
Or simply connect to the official servers when a proxy server is required.
Right now this will add a new config to the settings.xml called <proxy_server>.
This has to be edited to something like <proxy_server>http://127.0.0.1:8080</proxy_server> manually to use a proxy because no GUI exists right now.

Add Rudimentray Proxy Support

---

src/gui/GraphicPacksWindow2.cpp

On linux, the right side panel of the graphic pack window (2) is being cleared when clicking on any of the preset dropdown menus.
This PR prevents this from happening.

gui: keep shown graphic pack when clicking on preset dropdown

---

src/Cafe/Account/Account.cpp
src/Cafe/OS/libs/nn_act/nn_act.cpp

The name obtained from `GetMiiEx` is already swapped, so it shouldn't be swapped again. I've written a [minimal program](https://github.com/cemu-project/Cemu/files/9438841/miiname.rpx.zip) ([source](https://gist.github.com/IntriguingTiles/2d3d579d07a00eab2033596fec818942)) to test this that outputs the Mii name and the raw data of the Mii name in hex.
<details><summary>Screenshots</summary>
<p>
Previous behavior:
New behavior:
Behavior on console:
</p>
</details>
There are still some mystery 0x100s in the Mii name that shouldn't be there.

nn_act: Don't swap the Mii name again

---

CMakeLists.txt
cmake/FindZArchive.cmake
cmake/Findimgui.cmake
cmake/FindwxWidgets.cmake
cmake/Findzstd.cmake
dependencies/discord-rpc/src/CMakeLists.txt
src/CMakeLists.txt
src/Cafe/CMakeLists.txt
src/Cemu/CMakeLists.txt
src/Common/CMakeLists.txt
src/Common/platform.h
src/audio/CMakeLists.txt
src/config/CMakeLists.txt
src/gui/CMakeLists.txt
src/imgui/CMakeLists.txt
src/input/CMakeLists.txt
src/resource/CMakeLists.txt
src/util/CMakeLists.txt

This is still a work in progress, and is likely going to conflict with #9 (Cc: @Zopolis4)
With this PR I aim at making Cemu's build script more compatible with how Linux operates, so this mainly means that system dependencies will be used when possible.
I'll split the changes in different commits on purpose, so please don't squash this on merge.
Could potentially fix #1.

build: improve the Linux aspect of things

---

src/Cafe/Account/Account.cpp
src/Cafe/Filesystem/FST/FST.cpp
src/Cafe/HW/Latte/Core/FetchShader.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VKRBase.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanPipelineStableCache.cpp
src/Cafe/IOSU/legacy/iosu_act.cpp
src/Cafe/IOSU/legacy/iosu_crypto.cpp
src/Cafe/OS/libs/nn_idbe/nn_idbe.cpp
src/Cemu/Tools/DownloadManager/DownloadManager.cpp
src/Cemu/napi/napi_idbe.cpp
src/Cemu/ncrypto/ncrypto.cpp
src/Cemu/ncrypto/ncrypto.h
src/gui/ChecksumTool.cpp

`SHA1_Init`, `SHA1_Update`, `SHA1_Final`, `SHA256_Init`, `SHA256_Update`, `SHA256_Final` have been deprecated in OpenSSL 3.0 and will be removed in future versions.
- Replaced several simple calls to the `SHA1()` or `SHA256()` macro provided by OpenSSL
- Replaced other calls to deprecated functions with `EVP_DigestXXX` functions.
- Fixed an invalid sscanf format in DownloadManager
- Fixed unset return value  for `operator=` in VKRBase.h
- Fixed always-true checks for otpMem in `iosu_crypto`

Fix various compiler warnings and update OpenSSL hash functions

---

src/audio/DirectSoundAPI.cpp
src/audio/XAudio2API.cpp

[Bug #620](http://bugs.cemu.info/issues/620) Fixed crash when no audio devices are present
Steps to reproduce: 
1. In Window Sound manager, under Playback devices, disable all output devices
2. Start Cemu
3. Start any game
4. Cemu immediately closes
Updated functionality
1. When no audio devices are present on the PC, Cemu will no longer crash when starting a game.
2. Options-> General Settings ->  Audio, for both the APIs DirectSound and XAudio2, the TV/Device will now show as "Disabled" when no audio devices are present, previously it would display as "Primary Sound Driver"

Bug #620 Fixed crash when no audio devices are present

---

src/Cafe/HW/Latte/Renderer/Vulkan/VulkanPipelineStableCache.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h

Allowing multithreaded pipelines on Nvidia, if driver version 515 or higher is found

Nvidia Multithread Pipelines

---

BUILD.md

I've taken the liberty of reviving PR https://github.com/cemu-project/Cemu/pull/94 that got closed (he's still credited in this commit) and reworked it with some things that I wanted to improve regardless.
I'm only really able to test SteamOS 3.0, Ubuntu 20.04 and Manjaro, so let me know if anyone has any additional suggestions or notes about certain distros.

docs: Improve build instructions

---

src/gui/components/wxDownloadManagerList.cpp
src/gui/components/wxGameList.cpp
src/gui/components/wxTitleManagerList.cpp
src/gui/windows/PPCThreadsViewer/DebugPPCThreadsWindow.cpp

wxMenu ID = 0 is illegal on macOS.
`../src/osx/menuitem_osx.cpp(42): assert "id != 0 || pSubMenu != NULL" failed in wxMenuItem(): A MenuItem ID of Zero does not work under Mac`
Let's correct all the zero-starting ids to start with `wxID_HIGHEST + 1` resolving macOS GUI crashes.

Correct wxMenu ID to resolve macOS crash

---

CMakeLists.txt
src/CMakeLists.txt
src/Cafe/CMakeLists.txt
src/Cafe/GraphicPack/GraphicPack2.cpp
src/Cafe/HW/Latte/Core/LatteConst.h
src/Cafe/HW/Latte/Core/LatteThread.cpp
src/Cafe/HW/Latte/Renderer/Renderer.h
src/Cafe/HW/Latte/Renderer/Vulkan/CocoaSurface.h
src/Cafe/HW/Latte/Renderer/Vulkan/CocoaSurface.mm
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanAPI.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanAPI.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Common/CMakeLists.txt
src/gui/guiWrapper.cpp
src/gui/guiWrapper.h
src/util/Fiber/FiberUnix.cpp

Hi there!
As I promised here #52, this PR brings initial support for Vulkan over MoltenVK renderer on macOS.
This is enough to actually run some games to some extent. For now, I got a game to the stage where splash screen and loading screen appears, and actually works.
Some additional tinkering would be definitely necessary for the renderer to work on more non-trivial scenarios, but I guess it's a good step forward!
Geometry shaders and logic ops are explicitly turned off, so if any shader would emit code containing those features, it'll probably break. I believe we can work around this in future.
Some screenshots for you:

Initial implementation of macOS Vulkan renderer over MoltenVK

---

src/Common/CMakeLists.txt
src/Common/ExceptionHandler/ExceptionHandler_posix.cpp
src/Common/ExceptionHandler/ExceptionHandler_win32.cpp
src/gui/CemuApp.cpp

There's currently no overlap between the windows and posix
implementation of the exception handler so I split them into
different files for better clarity.
Added a signal handler for `SIGINT` to allow exiting on `CTRL+C`.
Note that like the rest of the program it does not exit cleanly and
triggers a `SIGABRT.`
Also removes function `CemuApp& wxGetAppWrapper()`
that was seemingly unused but declared with C linkage despite
returning a C++ reference, which was causing a warning.

Add SIGINT handler on posix systems 

---

src/Cafe/Account/Account.cpp
src/Cafe/IOSU/legacy/iosu_act.cpp
src/Cafe/IOSU/legacy/iosu_act.h
src/Cafe/OS/libs/nn_act/nn_act.cpp

I think there was a regression where Cemu 2.0 had the wrong endianness (BE) for accounts it created (which includes the default account). Meanwhile accounts obtained from the Wii U had a little-endian format and couldn't be obtained properly.
This fixes the endianness to be correct. I'm not sure where to correct it in Account too, hence the pull request.

nn_act: Fix account endianness

---

src/gui/components/wxGameList.cpp
src/gui/debugger/SymbolCtrl.cpp
src/gui/windows/TextureRelationViewer/TextureRelationWindow.cpp

Triggered when switching to icon view (and on program start afterwards) after
having modified column lengths in the list view:
```
0x00007ffff7a8ec4c in __pthread_kill_implementation () from /lib64/libc.so.6
0x00007ffff7a3e9c6 in raise () from /lib64/libc.so.6
0x00000000004ce24b in cemu_assert_debug (_condition=false) at /root/cemu/src/gui/../Common/precompiled.h:350
0x0000000000c0f30d in CemuApp::OnAssertFailure (this=0x2dfdc80, file=0x2ec4880 L"/root/cemu/dependencies/vcpkg/buildtrees/wxwidgets/src/v3.2.0-b1a1c2cb85.clean/src/generic/listctrl.cpp", line=3473, func=0x32cec00 L"SetColumnWidth", cond=0x32ce750 L"\"InReportView()\"", msg=0x333ab70 L"SetColumnWidth() can only be called in report mode.") at /root/cemu/src/gui/CemuApp.cpp:164
0x00000000010f2c04 in wxDefaultAssertHandler …
```

Fix UI asserts

---

src/Cafe/CMakeLists.txt
src/Cafe/HW/Latte/Core/LatteIndices.cpp

Resolves https://github.com/cemu-project/Cemu/issues/144

Per-function target attribute on clang and GCC.

---

CMakeLists.txt
src/CMakeLists.txt
src/Cafe/CMakeLists.txt
src/Cemu/CMakeLists.txt
src/Common/CMakeLists.txt
src/asm/CMakeLists.txt
src/audio/CMakeLists.txt
src/config/CMakeLists.txt
src/gui/CMakeLists.txt
src/imgui/CMakeLists.txt
src/input/CMakeLists.txt
src/resource/CMakeLists.txt
src/util/CMakeLists.txt

Some bits originated from #75
- Fix `target_precompile_headers()` usage; the CemuCommon target exposes the `src/Common/precompiled.h` precompiled header as part of its public interface with `target_precompile_headers(CemuCommon PUBLIC precompiled.h)`, so all the other targets wanting to use the precompiled header have to link to the CemuCommon target with `target_precompile_headers(TargetName PRIVATE CemuCommon)`.
- Set the project version to 2.0
- Set `RUNTIME_OUTPUT_DIRECTORY` instead of only their `_DEBUG` and `_RELEASE` variants, fixing the compilation when neither build types are defined (see https://github.com/cemu-project/Cemu/issues/1#issuecomment-1229359719)
- Use a consistent indentation style (tabs, like in the .cpp files)
- Use "modern" variants of some functions, e.g. …

build: minor refactoring and fixes

---

.gitignore
src/gui/DownloadGraphicPacksWindow.cpp

The request for grabbing the gfx pack download URL was broken because of inserting the build suffix without escaping it, but it's not really necessary anyway. I also changed the URL since it's nicer to have a separate API for post 2.0 releases.
Also tweaked .gitignore

Update graphic pack url query request

---

BUILD.md

This fixes an issue I had about bootstraping vcpkg because curl wasn't found.

Add curl as linux build dependency

---

src/gui/components/wxGameList.cpp

Game ordering was broken when clicking on the name column or adding/removing a favorite.
Unlike the standard lib's that requires a strict weak ordering comparator, wxWidgets needs a compare function that returns a negative number, 0 or a positive number when entries are respectively lower than, equal to and greater than.
Fixed using C++20 comparison API.

Fix game list ordering & Favorite checkbox

---

src/Cafe/OS/libs/h264_avc/H264Dec.cpp

This cause fail to playback the 1080p videos from the BotW Switch version if BotW's TitleRegion is JP.

fix H264_IsBotW() return false while BotW's TitleRegion is JP

---

.github/workflows/build.yml
.github/workflows/deploy_experimental.yml
.gitignore
src/CMakeLists.txt

There was an issue where multi-configuration generators would put the binary in a `/<config>` subdirectory relative to bin. This was due to some oversight and should now be fixed.
In regards to RUNTIME_OUTPUT_DIRECTORY from the cmake documentation:
> This property specifies the directory into which runtime target files should be built. The property value may use [generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#manual:cmake-generator-expressions(7)). Multi-configuration generators ([Visual Studio](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators), [Xcode](https://cmake.org/cmake/help/latest/generator/Xcode.html#generator:Xcode), [Ninja Multi-Config](https://cmake.org/cmake/help/latest/generator/N …

Name output binary Cemu_<CONFIG> and always place it in /bin/

---

src/config/CemuConfig.cpp

`std::is_same_v<decltype(0LL), int64_t>` does not evaluate the same on Linux Clang and MSVC. MSVC returns true but Clang and GCC both returns false resulting in failing to read the game id from the XML file and therefore rebuilding the cache.
Solution: Don't rely on the type of `0LL` and `0ULL` literals but explicitly provide the type of the field we are trying to read.
Fixes #164

Fix the reloading of game cache from settings.xml on Linux

---

src/resource/cemu.rc

Clang has issues with utf16 and MSVC does not like utf8. So ANSI it is

Use ANSI encoding for cemu.rc (remove utf8 BOM)

---

CMakeLists.txt

Cemu requires fmt 9.1.0 after https://github.com/cemu-project/Cemu/commit/0ed4fdcd789081f210d9587b24af7e5c050cfc55

build: update required fmt version

---

src/Cafe/HW/Espresso/PPCTimer.cpp

`_MSC_VER < 1923` evaluates to `true` on every compiler that does not define `_MSC_VER`, so this expression `#if _MSC_VER < 1923 || defined(__clang__)` almost always evaluates to true and is potentially misleading. Replaced with a (hopefully) clearer condition.

Improved clarity.

---

src/gui/input/settings/DefaultControllerSettings.cpp
src/gui/input/settings/WiimoteControllerSettings.cpp

This is needed to avoid having the Controller settings window black on Linux

Set timer milliseconds for "Controller settings"

---

src/Cafe/HW/Espresso/PPCTimer.cpp
src/Common/precompiled.h
src/asm/x64util.h
src/asm/x64util_masm.asm

As discussed in https://github.com/cemu-project/Cemu/pull/188. Implemented _udiv128 (on compilers that don't have it built in) using 128 bit types. Some dubious performance testing [here](https://github.com/tomlally/udiv128_test).

Cleanup udiv128

---

src/Common/ExceptionHandler/ExceptionHandler_posix.cpp
src/gui/CemuApp.cpp
src/gui/MainWindow.cpp

The best ExitProcess alternative for Linux is _exit since it doesn't call exit handlers.
This fixes also #178 since, with exit, it aborts due to some std::threads not correctly joined.
In the future, if VS2022 supports it, we may use std::jthread instead of std::thread since they automatically joins; when jthread will be used, `CemuApp::OnExit` may be removed since ExitProcess/_exit will not be necessary anymore

Use _Exit instead of exit under Linux

---

src/Common/unix/FileStream_unix.cpp

In some cases when trying to open a directory it's opened as a file instead because no error is reported when creating a FileStream for a directory.

fix for when file open is successful but the path isn't a file

---

src/Cafe/CafeSystem.cpp
src/Cafe/Filesystem/FST/fstUtil.h
src/Cafe/Filesystem/fsc.cpp
src/Cafe/Filesystem/fsc.h
src/Cafe/Filesystem/fscDeviceHostFS.cpp
src/Cafe/Filesystem/fscDeviceRedirect.cpp
src/Cafe/Filesystem/fscDeviceWua.cpp
src/Cafe/Filesystem/fscDeviceWud.cpp
src/Cafe/GraphicPack/GraphicPack2.cpp
src/Cafe/OS/libs/coreinit/coreinit_FS.cpp
src/Cafe/OS/libs/nn_acp/nn_acp.cpp
src/Cafe/TitleList/SaveList.cpp
src/Cafe/TitleList/TitleInfo.cpp
src/Cafe/TitleList/TitleList.cpp
src/Common/precompiled.h
src/config/ActiveSettings.h
src/config/CemuConfig.cpp
src/gui/GameUpdateWindow.cpp
src/gui/MainWindow.cpp
src/gui/MemorySearcherTool.cpp
src/gui/TitleManager.cpp
src/gui/components/wxGameList.cpp
src/gui/components/wxTitleManagerList.cpp
src/gui/dialogs/SaveImport/SaveImportWindow.cpp
src/gui/dialogs/SaveImport/SaveTransfer.cpp
src/main.cpp

Aside from being more robust in general, this should fix exceptions some Linux users had when their locale did not translate to/from wchar.

FSC: Replace wstring paths with utf8 encoded strings

---

src/gui/CemuApp.cpp

According to the [wxWidgets documentation](https://docs.wxwidgets.org/3.0/classwx_key_event.html#a6fddcd170d05b0852a7eb2a0cb730795) :
> Under GTK, the raw key code is the keyval field of the corresponding GDK event.
And some keyevents have a raw key code that is greater than 256, which leads to undefined behavior.
In some cases, it crashes the app. For example, when I press the fn+F12 to increase the volume, which has a keyval value of 0x1008ff13 (according to the [GTK source code](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/gdkkeysyms.h)), the app crashes.

Check if raw keycode is out of bounds

---

.github/workflows/generate_pot.yml
src/gui/components/wxTitleManagerList.cpp
src/gui/debugger/RegisterWindow.cpp
src/gui/debugger/SymbolWindow.cpp
src/gui/input/panels/ClassicControllerInputPanel.cpp
src/gui/input/panels/ClassicControllerInputPanel.h
src/gui/input/panels/ProControllerInputPanel.cpp
src/gui/input/panels/ProControllerInputPanel.h
src/gui/input/panels/VPADInputPanel.cpp
src/gui/input/panels/VPADInputPanel.h
src/gui/input/panels/WiimoteInputPanel.cpp
src/gui/input/panels/WiimoteInputPanel.h
src/input/emulated/ClassicController.cpp
src/input/emulated/ProController.cpp
src/input/emulated/VPADController.cpp
src/input/emulated/WiimoteController.cpp
src/input/emulated/WiimoteController.h

In addition to a few small UI strings improvements, this PR makes the gamepad button names translatable (home, left, right, click), except A, B, X, Y etc. which are always the same in all languages.
To accomplish that, I've used the [wxTRANSLATE](https://docs.wxwidgets.org/3.2/group__group__funcmacro__string.html#gab8862de0f74049708bfea75ae9e14c45) macro to mark button names as translatable (so that they get included in the POT file) and then called [wxGetTranslation](https://docs.wxwidgets.org/3.2/group__group__funcmacro__string.html#ga49dcdc17d82a627b7a50d401f1a37d69) in the GUI (actually, in the `InputPanel`s) to retrieve the translated names.
While I was at it, I've deduplicated a lot of the code that creates the input fields for each controller button in `InputPanel` classes. 
Last …

More l10n improvements and add workflow to generate POT file

---

src/Cafe/CMakeLists.txt

fixes the regression brought in by #249 by adding the scope option that is required by target_sources

Fix a small regression when building in Macos

---

CMakeLists.txt
src/gui/GeneralSettings2.cpp
src/gui/TitleManager.cpp
src/gui/components/wxGameList.cpp
src/resource/CMakeLists.txt

This fixes some issues when building on macOS and for macOS
Reasoning behind changes
1. For some reason when building on macOS, OBJC and OBJCXX need to be explicitly enabled else an error involving [precompiled.h](https://github.com/cemu-project/Cemu/tree/main/src/Common) occurs. Is only enabled on macOS, no side effects. Credits to OatmealDome
2. changing strong ordering to weak ordering. There exists implicit conversion from strong to weak and in our case it shouldn't produce any side effects. Three way comparison on strings produces weak_ordering which can't be converted to strong_ordering. Functionality in all cases should be kept the same while adding support for macOS.
3. Uses the raw PNG bytes found in [resources/embedded](https://github.com/cemu-project/Cemu/tree/main/src/resource/ …

Fix some issues with building on macOS

---

src/gui/debugger/DebuggerWindow2.cpp
src/gui/input/InputSettings2.cpp
src/resource/cemu.rc

- Fixed an issue where the toolbar icons for the debugger were resized to 1x1
- On Windows we now load the PNG UI icons from the header-embedded pngs (`resource/embedded`) instead of via `cemu.rc` to match behavior of other platforms

Fix 1x1 symbols in debugger window + Load icons from headers on all platforms

---

.github/workflows/build.yml

When building vcpkg packages from scratch, the Windows CI can sometimes run out of disk space. Running vcpkg with `--clean-after-build` should fix this as it cleans up some of the temporary data that is generated during package building.
I also removed the MSVC workaround which is no longer necessary ([relevant issue](https://github.com/actions/runner-images/issues/6091)).

CI: Fix Windows build running out of disk space

---

src/Cafe/HW/Latte/Core/LatteTextureLoader.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

We normally map Latte's R4G4 texture format to `VK_FORMAT_R4G4_UNORM_PACK8`. But on some AMD and Intel GPUs this format is not available or has limited usage. In that case we fall back to `VK_FORMAT_R4G4B4A4_UNORM_PACK16` as a substitute format. This PR fixes the incorrect channel order we had in the conversion code.
Resolves a known problem where the rupee counter in Twilight Princess is invisible on affected GPUs. This may also fix other issues mentioned in #212 
Before:
After:

Vulkan: Fix incorrect encoding for substituted R4G4 format

---

BUILD.md

This PR includes instructions on how to install brew on macOS, which is required for installing the dependencies to build Cemu.

include instructions to install brew on macos build instructions

---

BUILD.md

llvm is a required package to build cemu on Arch Linux.
See #307

Build.md: Arch linux: Add llvm as a required dependency

---

src/Cafe/OS/libs/nn_nfp/AmiiboCrypto.h
src/Cafe/OS/libs/nn_nfp/nn_nfp.cpp

Improves the amiibo implementation by correcting the NFC structs, fixing the corrupted bytes of `dynamic lock` and incrementing/reporting the write counters.
With this change amiibos should be compatible with yuzu. Some games that reported `different amiibo detected` after writing or deleting some data should be fixed as well.

service: nfp: Fix corruption, correct structs and use write counters

---

src/Cafe/HW/Latte/Renderer/Vulkan/VKRBase.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanPipelineCompiler.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanPipelineCompiler.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

Should fix a warning in the Vulkan validation layer and avoid a sigtrap in MoltenVk. Visually it should make no difference because implementations just ignore the blending state for integer formats.

Vulkan: Always disable blending for integer formats

---

src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h

Workaround for R5_G6_B5_UNORM pixel formats which is not supported on macOS. Allows games such as BOTW and SM3DW to boot.
Credits to @Tillsunset

Workaround for unsupported format R5_G6_B5_UNORM

---

src/Cafe/HW/Latte/Core/LatteTextureLoader.h
src/Cafe/HW/Latte/Renderer/OpenGL/OpenGLRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

This _should_ decode `R4_G4_UNORM` and `R4_G4_B4_A4_UNORM` to `VK_FORMAT_R8G8B8A8_UNORM`. This is my first time writing something like this so I'm not entirely sure it's accurate, and I don't actually know where these textures are visible so I can't see them either. I did a few tests and it _seems_ to be okay though?
This is useful on macOS, where MoltenVK does not support the two texture formats.

dedicated decoder for R4G4 and R4G4B4A4 to R8G8B8A8

---

src/Cafe/OS/libs/h264_avc/H264Dec.cpp

fix the underlying issue of H264DECEnd() getting passed an nullptr instead of a valid ptr. Aligned_alloc needs size to be multiple of alignment

Workaround for the h264 video crash on macOS

---

src/Cafe/OS/libs/h264_avc/H264Dec.cpp

replace aligned_alloc with posix_memalign, no more allocating padding bytes.
Really sorry for the multiple PRs, I found this as the last one merged.

memory optimization, using posix_memalign

---

src/CMakeLists.txt
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanAPI.h
src/Common/ExceptionHandler/ExceptionHandler_posix.cpp
src/Common/precompiled.h

This PR does the following:
Crash backtraces go from looking like this:
To looking like this:
The PR also increases the amount of lines cemu tries to retrieve because I've encountered a situation where the backtrace was incomplete.
Caveats:
- For a process to be able to get symbol information from linux's backtrace functions the linker flag `-rdynamic` needs to be enabled. This increases Release executable size by 4.4 MiB.
- Symbols are exported implicitly.
- I'm not sure the addr2line tool supports de-mangled symbol names so people using it may run into trouble. This could be a problem if a bug is hard to reproduce and all they have is a stacktrace, though AFAIK that tool requires a debug build to function anyway and I don't think it'll be common for people to find hard to reproduce bugs …

Linux: Print demangled symbols on backtrace

---

.gitignore
src/Cafe/IOSU/legacy/iosu_boss.cpp
src/Cemu/napi/napi_ec.cpp
src/Cemu/napi/napi_helper.cpp
src/Cemu/napi/napi_idbe.cpp
src/Cemu/napi/napi_version.cpp
src/config/ActiveSettings.cpp
src/config/ActiveSettings.h
src/config/CMakeLists.txt
src/config/CemuConfig.cpp
src/config/CemuConfig.h
src/config/LaunchSettings.cpp
src/config/LaunchSettings.h
src/config/NetworkSettings.cpp
src/config/NetworkSettings.h
src/gui/GeneralSettings2.cpp
src/gui/GeneralSettings2.h
src/gui/guiWrapper.cpp
src/main.cpp

This PR adds support for third party servers (currently Pretendo only but can be expanded later) support natively and Indication on top of which Network Service the user is using.
This also Adds an option to disable SSL Verification checkbox if third party servers do not have SSL (like Pretendo atm).

Added Native Pretendo and custom URLs support

---

src/Cafe/HW/Latte/Core/LatteBufferCache.cpp

This PR replaces `std::unordered_set` in LatteBufferCache with a custom high-performance sparse bitset implementation.
Benchmark from my Steam Deck. Before:
With these new changes I get a 60% improvement in FPS:
The FPS boost will not be the same for each game as different workloads have different bottlenecks, but at least some improvement should be seen across the board. It also does not increase performance on Windows noticeably because MSVC's implementation of unordered_set already behaved in just the way we needed for good performance.
In depth technical explanation:
Seems like `std::unordered_set` cannot be blindly trusted for performance critical code. The performance characteristics differ based on which STL is used as each one comes with a different underlying algorithm. …

Linux/MacOS: Greatly improve performance

---

src/util/crypto/crc32.cpp

The logs saying CRC mismatch on macOS is fixed. ~~I searched for the "\_\_BYTE\_ORDER" macro [here](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html) but found "\_\_BYTE_ORDER\_\_"~~
Now using [std::endian](https://en.cppreference.com/w/cpp/types/endian) and handle mixed endian

Fixes the CRC errors

---

src/input/api/DSU/DSUMessages.cpp
src/main.cpp
src/util/crypto/crc32.cpp
src/util/crypto/crc32.h
vcpkg.json

Since libpng is ubiquitous we should just link it dynamically on Linux. Solves the issues discussed in #376
I also removed the dependency on boost-crc used only in the DSU code since we already have a CRC implementation.

Linux: Always use libpng from system

---

dependencies/vcpkg_overlay_ports/wxwidgets/vcpkg.json

After #381 cemu was still linking libpng statically but this fixes it.

Remove libpng dependency from wxwidgets for linux platform.

---

src/Cafe/CafeSystem.cpp
src/gui/MainWindow.cpp
src/gui/MainWindow.h

This PR makes it so Discord Rich Presence loads the name of the title instead of title ID and also loads it with your Cemu Language  Preference.

Fixed Discord Rich Presence not working on games that are on MLC

---

src/gui/CemuApp.cpp
src/gui/CemuApp.h
src/gui/GeneralSettings2.cpp
src/util/helpers/helpers.cpp

- Update title manager when you clear the mlc path in settings and show a message when it's not accessible.
- Make sure TestWriteAccess never throws an exception
- Rewrote the infinite loop in SelectMLCPath using a goto which I know might be controversial. It can be changed back if needed but I think the code makes more sense like this.

bugfix: title manager doesn't update when clearing MLC path in settings.

---

src/Cafe/CafeSystem.cpp
src/Cafe/TitleList/TitleInfo.cpp
src/gui/MainWindow.cpp
src/gui/components/wxGameList.cpp
src/gui/components/wxGameList.h

This PR updates the short name of the titles in the title list when the user switches language without requiring a restart to update.
This PR also updates the Window/Discord Name by having it fallback to the English Strings if there is not an available string in the selected language.

Auto update game title name when Language is changed and fallback to English name if not available

---

src/Cafe/GraphicPack/GraphicPack2.cpp
src/Cafe/HW/Latte/Core/LatteShader.cpp
src/Cafe/OS/libs/gx2/GX2.cpp
src/tools/ShaderCacheMerger.cpp

Graphics pack custom shader matching fails on linux (and most likely macos) because `%I64x` is a windows specific format specifier. The solution is to use `SCNx64` instead, except in inherently platform dependent code (e.g. `src/Common/ExceptionHandler/ExceptionHandler_win32.cpp`).

Use cross platform format specifiers (fixes #387)

---

src/Cafe/Filesystem/fsc.cpp
src/Cafe/Filesystem/fsc.h
src/Cafe/IOSU/fsa/iosu_fsa.cpp

Translates paths for remove, makeDir and rename.
This fixes issues where the working directory was not respected for those commands.

FSA: Add missing path translations

---

src/Cafe/HW/Latte/Renderer/OpenGL/OpenGLRenderer.cpp

This fixes #222.
The back buffer is not attached when clearing, causing the previously bound framebuffer object to be cleared instead. The solution is to bind the back buffer before clearing. In the vulkan renderer it is done in the same way.

OpenGL: Bind back buffer before clearing (fixes #222)

---

src/Cafe/HW/Latte/Core/Latte.h
src/Cafe/HW/Latte/Core/LatteThread.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRendererCore.cpp
src/audio/CubebAPI.cpp
src/gui/CemuUpdateWindow.cpp
src/util/Zir/Core/IR.cpp

replaces volatile with std::atomic
always true assert
bitwise operation on enum with equivalent builtin enum
printf format with proper unsigned long long
counter operation that always returns false

Fixes some compiler warnings

---

.github/workflows/build.yml
BUILD.md

Fixes #428.
libpulse-dev was added to Ubuntu build instructions in https://github.com/cemu-project/Cemu/commit/7d461d1658aab5d8fe9fa8848ae4627963fa6a93 but never added to the GitHub workflow.
Before this gets approved, [a build with this change is available here](https://github.com/jn64/Cemu/actions/runs/3350536261#artifacts) if any other Ubuntu users wish to test.
I also sorted the dependencies to make it easier to read/diff in the future.
---
I'm guessing #374 is related, as well as various mentions of no sound in #107 ([1](https://github.com/cemu-project/Cemu/issues/107#issuecomment-1259151157), [2](https://github.com/cemu-project/Cemu/issues/107#issuecomment-1292643250))

Add libpulse-dev to CI build

---

src/gui/MainWindow.cpp

The current full screen option is broken on macOS. It disables the menu and task bar on all desktops and monitors when in focus. It is also incorrectly positioned, top portion is off screen. Rendering the menu bar unreachable.
This opts to use the native full screen option through wxWidgets, fixing the above issues. Also enables the auto hiding of the menu and task bar and getting rid of the rounded corners in full screen. This effect can already be achieved by using the full screen button on the window instead of the "alt+enter" shortcut.
I'm assuming cemu uses a borderless window mode for full screen, this usually has issues on macOS. A similar effect can be seen on firefox when using a video player's full screen as opposed to the native full screen(clicking the green button on macOS)

Fix fullscreen on macos

---

src/input/api/DSU/DSUControllerProvider.cpp

the default flags argument passed here is boost::asio::ip::tcp::resolver::query::address_configured, which means that the call should only resolve IPv4/IPv6 addresses if a non-loopback IPv4/IPv6 address is configured for the system.
Signed-off-by: Schspa Shi <schspa@gmail.com>

DSUController: fix crash when running on offline mode.

---

src/imgui/imgui_extension.cpp
src/resource/CMakeLists.txt
src/resource/embedded/fontawesome.S
src/resource/embedded/fontawesome_macos.S

On linux we don't have access to resource files so we have to resort to converting files to C source code.
For fontawesome this would result in a 1MB C source file from a 160KB .ttf file. Clearly not acceptable.
This is the next best thing. Short assembly file that exposes symbols to the .ttf file data.
I'm creating this pull request to trigger CI to check if mac supports it too. ~If not I'll make it linux only.~
Confirmed working on macOS and Linux.

Non-windows: Link fontawesome into executable.

---

src/Cafe/CafeSystem.cpp
src/Cafe/OS/libs/mic/mic.cpp
src/audio/CMakeLists.txt
src/audio/CubebInputAPI.cpp
src/audio/CubebInputAPI.h
src/audio/IAudioInputAPI.cpp
src/audio/IAudioInputAPI.h
src/config/CemuConfig.cpp
src/config/CemuConfig.h
src/gui/GeneralSettings2.cpp
src/gui/GeneralSettings2.h
src/main.cpp

This PR implements microphone support by more or less completing the existing mic HLE lib alongside a new `IAudioInputAPI` interface similar to the normal one for output. Only supports cubeb for now but can be extended to DirectSound with another `IAudioInputAPI` implementation in the future.
A more detailed overview of the changes:
- Made a new `IAudioInputAPI` interface for handling audio input, since there were too many differences to how stuff is handled to include it `IAudioAPI` interface. Currently only implemented by `CubebInputAPI` but can be implemented by other APIs.
- Implemented feeding microphone samples from `IAudioInputAPI`, falls back to generating samples with controller button if device is disabled.
- Changed `MIC_HANDLE_DRC0` and `MIC_HANDLE_DRC1` from 100/101 to 0/1 …

Implement proper microphone support

---

src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRendererCore.cpp

This change ends the current render pass when cemu detects a self-dependency within it. This fixes #267.
However the performance implications of separating the draw calls into multiple render passes and the broader barriers are unknown.
~~My test in breath of the wild showed an acceptable reduction in worst %.1 framerate from 69.7fps to 56.3fps. with 97th percentile being down only 2 fps from 102 to 100.~~ (Bad testing methodology)
Different GPUs/OS's/drivers may get different outcomes so this change requires performance testing.
**Accurate barriers must be enabled for this to work**

Vulkan: Experimental fix for self-dependency barriers during render pass. (performance testing needed)

---

src/Cafe/IOSU/legacy/iosu_crypto.cpp
src/Cemu/ncrypto/ncrypto.cpp
src/gui/input/InputSettings2.cpp
src/input/api/SDL/SDLController.cpp

Having the same SDL controller active more than once and then removing one instance caused Cemu to crash

Fix input settings not refreshing + SDL controller crash

---

.gitignore
src/Cafe/HW/Latte/Core/LatteOverlay.cpp
src/Cafe/HW/Latte/Core/LatteShaderCache.cpp
src/Cafe/OS/libs/erreula/erreula.cpp
src/Cafe/OS/libs/swkbd/swkbd.cpp

1. As commented in imgui.h, should call a matching End() for each Begin()  regardless of its return value. Tested in BotW, this seems to improve performance very slightly.
2. Fix softkeyboard, click on background overlay will bring it to front and cover the softkeyboard.

ImGui: match all begin/end

---

src/gui/canvas/OpenGLCanvas.cpp

Apparently in order for a canvas to be able to swap buffers, on linux the context needs to be current for that canvas.

Linux OpenGL: Fix gamepad not updating

---

src/gui/GeneralSettings2.cpp

Disable the Discord checkbox when compiled with `-DENABLE_DISCORD_RPC=OFF`.
I'm not a programmer (but I play one on TV), so please let me know where the code should go if not here.

Disable Discord checkbox based on build option

---

src/CMakeLists.txt

As discussed in discord. Rely on distro policy to choose PIE, but do enforce a non-executable stack.

Change security flags

---

src/Cafe/HW/Latte/Renderer/Vulkan/SwapchainInfoVk.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/SwapchainInfoVk.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

- Fix use after free bug in CreateSwapchainCreateInfo
- Always use minImageCount. Unclear why it was min+1. This also reduces input lag on double buffered vsync by one frame.
- Remove unnecessary semaphore, it is unnecessary because the image is awaited by means of a fence.
- Don't submit command buffer in AcquireNextSwapchainImage
- Don't wait for fence when recreating; already waited for device to be idle.
- Remove barrier before present. VkQueuePresentKHR is set to wait for the presentSemaphore which becomes signalled when the command buffer that writes to the swapchain image finishes execution. No barrier is required because: ```Any writes to memory backing the images referenced by the pImageIndices and pSwapchains members of pPresentInfo, that are available before vkQueuePresentKHR …
```

Vulkan: Further simplify swapchain code

---

src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

When a swapchain becomes suboptimal after an acquire for rendering, SwapBuffer would recreate the swapchain and acquire a new image from it which would get filled in with black because the content is undefined, resulting in black flickering when resizing.
By changing the order in AcquireNextSwapchainImage it'll always try to present the suboptimal image it already acquired and drew content to and drop the image if it is out of date and cannot be used. Then when no image is reserved anymore the next acquire will recreate the swapchain.

Vulkan: Fix flicker on resize

---

src/gui/MainWindow.cpp

Whenever any key except for the arrow keys is pressed, macOS generates an error sound.
To my understanding, this is caused because event.Skip() causes wxWidgets to keep looking for further handlers.
However as no further handling occurs, macOS reports this as an unhandled event.
I am leaving this as a draft for now, as I cannot test if this has any drawbacks on other platforms than macOS.
Also I am unsure which purpose event.Skip() serves in the other occurences. Only one occurrence has been modified, which fixed the issue without apparent drawbacks.
However, if not Skipping has no drawbacks on other platforms and other occurences in this file, the other occurences should be modified as well.

macOS: fix error sound for every KB keypress on render canvas

---

CMakeLists.txt
cmake/FindGTK3.cmake
src/CMakeLists.txt
src/Cafe/CafeSystem.cpp
src/Cafe/HW/Latte/Core/Latte.h
src/Cafe/HW/Latte/Core/LatteRenderTarget.cpp
src/config/ActiveSettings.cpp
src/gui/CMakeLists.txt
src/gui/CemuApp.cpp
src/gui/guiWrapper.cpp
src/gui/guiWrapper.h
src/input/api/Keyboard/KeyboardController.cpp

This requires GTK headers so I added GTK as a dependency (no actual new dependency, wxwidgets already linked libgtk). Which also allows replacing all explicitly dynamically loaded calls with normal calls.
This also changes the way KeyboardController stops sending input after loss of focus. I changed the keyboard code that was already in gui_wrapper/CemuApp so it works as intended. Using the KILL_FOCUS event didn't work because pressing tab would immediately trigger that event and unpress all keys. The ACTIVATE_APP event doesn't have that issue. Now that the keyboard state tracking code updates to make all keys unpresed when focus is lost KeyboardController doesn't need to check if the windows is active anymore.

Fix gamepad hotkey and game profile setting

---

src/Cafe/HW/Latte/Renderer/Vulkan/SwapchainInfoVk.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/SwapchainInfoVk.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h

#502 adopted a swapchain sync method that is correct in theory but is not commonly used. 
This changes the sync method back to what was used before.
The [validation layer](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/12) appears to not have made up their mind about whether using only a fence is valid and one of the authors of the vulkan specification says it is unintended and basically advises against it [here](https://github.com/KhronosGroup/Vulkan-Docs/issues/117#issuecomment-200357476)
This PR also ups the minimum swapchain image count to at least two images (not min+1 which might be > 2 causing unnecessary input lag and wasting resources). Using only one swapchain image caused a freeze on AMD windows drivers when switching to fullscreen.
One of the issues that popped …

Vulkan: return to more conventional swapchain sync method, encapsulate more code

---

src/Cafe/GraphicPack/GraphicPack2.cpp

some escaped characters inside a raw string caused an exception

Fix shader preset regex

---

src/Cafe/GraphicPack/GraphicPack2.cpp

apologies, I thought the first backslash was a left over escape character and my testing wasn't thorough enough. Turns out it was a regular character to search for.
Before no graphics pack.
Before with graphics pack(serfrost clarity preset)
After with graphics pack
note the extra blue tint from the graphics pack and not black screen.

Fix black screen when graphics packs are used and regression in #536

---

src/gui/guiWrapper.h

Control doesn't seem to like to be picked up still. Might be because I'm not using an apple keyboard.
Have to hold tab, press control, release tab, then press tab again to activate the toggle hotkey.
Could also be because macOS is capturing control for something.
At the very least this should fix the gamepad toggle when someone presses A on their keyboard (keycode 0 😅)

macOS: Add platform specific control/tab keycodes

---

src/Common/precompiled.h

std::chrono::steady_clock::now() may be slower than clock_gettime() (a direct call and vDSO). For an even faster implementation, cycle counting (through rdtsc) is likely needed, but this level of depth is unnecessary.

fix: use an alt implementation for tick_cached()

---

src/Cafe/OS/libs/swkbd/swkbd.cpp

On macOS delete (hex 7f) is used instead of backspace (hex 8) for removing a character before the cursor

macOS: fix software keyboard input delete

---

.github/workflows/build.yml
dist/linux/appimage.sh

- Fix incorrect recursive copy. Previously, if you didn't delete AppDir between builds, `bin/` would be copied *into* an existing `AppDir/usr/share/Cemu`
- Add metainfo file. [According to appstream docs](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-introduction), `metainfo.xml` is correct, but [the warning from linuxdeploy](https://github.com/cemu-project/Cemu/actions/runs/3640469545/jobs/6145427858#step:5:1494) says `appdata.xml` so that's where I put it.

Minor AppImage fixes

---

src/Common/precompiled.h
src/Common/unix/platform.cpp
src/util/highresolutiontimer/HighResolutionTimer.cpp

clock_gettime_nsec_np is an optimization of clock_gettime, roughly 90% time needed from some [testing](https://gist.github.com/Tillsunset/61d8681c7b681b8f0922fca068db6ca1). It is specific to macOS though.
CLOCK_MONOTONIC_RAW_APPROX is another potential optimization for macOS, roughly 50% time needed compared to CLOCK_MONOTONIC_RAW. But typically only guarantees 1 millisecond accuracy. Its potential usage and overall speedup is extremely debatable. I could see it potentially being used in GetTickCount() and tick_cached(). 
clock_getres also always returns 1 nanosecond, I'm not sure if that is the intended purpose when used in HighResolutionTimer::getFrequency(). Feedback needed

Macos Optimization

---

src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

Fixes macOS crash on newer versions.

Vulkan: Use the correct resolution for out-of-date check

---

.gitignore
src/Cafe/HW/Espresso/Const.h
src/Cafe/HW/Espresso/Interpreter/PPCInterpreterALU.hpp
src/Cafe/HW/Latte/Core/LatteCommandProcessor.cpp
src/Cafe/HW/Latte/Core/LatteTextureLoader.cpp
src/Cafe/HW/Latte/Core/LatteTextureReadback.cpp
src/Cafe/HW/Latte/LegacyShaderDecompiler/LatteDecompilerEmitGLSLHeader.hpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanPipelineStableCache.cpp
src/Cafe/HW/MMU/MMU.h
src/Cafe/IOSU/fsa/iosu_fsa.cpp
src/Cafe/OS/libs/coreinit/coreinit.cpp
src/Cafe/OS/libs/coreinit/coreinit_FS.cpp
src/Cafe/OS/libs/coreinit/coreinit_MemoryMapping.cpp
src/Cafe/OS/libs/coreinit/coreinit_Spinlock.cpp
src/Cafe/OS/libs/coreinit/coreinit_Thread.cpp
src/Cafe/OS/libs/coreinit/coreinit_Thread.h
src/Cafe/OS/libs/padscore/padscore.cpp
src/Cafe/OS/libs/vpad/vpad.cpp
src/Cemu/Logging/CemuLogging.cpp
src/Cemu/Logging/CemuLogging.h
src/Common/precompiled.h
src/gui/MainWindow.cpp
src/input/api/ControllerState.h

Fixes:
- Potential random crash when reading controller button state
- Many Unity based games are working again (restored missing coreinit.OSMapMemory)
- General improvements to DS VC emulation. Yoshi's Island DS is now playable, other games still freeze during menus.
- Fixed z-sorting in DS VC, so backgrounds don't get drawn above everything else now.
I also restored and tweaked an optimization that avoids expensive texture readbacks if they are redundant. I'm not sure when this broke but either way it's working again now. In DS titles this boosts performance by a factor of 5x and in BotW the FPS shouldn't drop as much anymore when triggering dynamic fire (e.g. when burning grass). Other games don't really use readback frequently enough for it to make a difference.
Demonstration of …

Various fixes + readback performance improvement

---

src/gui/components/wxGameList.cpp

Occurs if gamelist is Icons or SmallIcons style everytime cemu starts

GameList: fix the last column is hidden

---

src/Cafe/HW/Latte/Core/LatteOverlay.cpp
src/Cafe/HW/Latte/Core/LatteShaderCache.cpp
src/Cafe/HW/Latte/Core/LatteThread.cpp
src/Cafe/HW/Latte/Renderer/OpenGL/OpenGLRenderer.cpp
src/Cafe/HW/Latte/Renderer/Renderer.cpp
src/Cafe/HW/Latte/Renderer/Renderer.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/imgui/imgui_extension.cpp

Does what the title says and also removes some duplicate code from the cache loading screen.
Feedback very welcome.
Perhaps the context initialization code should go in the Renderer Constructor/destructor instead of Initialize and Shutdown?
Fixes: #651

Separate imgui contexts for TV and Pad windows.

---

src/Cafe/HW/Latte/Core/LatteShaderCache.cpp

Fixes: #666
I did not look at the flags closely enough.
Also fix a bug where the progress bar would size according to the gamepad context. Fixed by getting the context IO after ImguiBegin switches to the correct context.

Add back missing flag to keep background image in background

---

.gitignore
README.md
src/Cafe/CMakeLists.txt
src/Cafe/CafeSystem.cpp
src/Cafe/HW/Espresso/Debugger/Debugger.cpp
src/Cafe/HW/Espresso/Debugger/Debugger.h
src/Cafe/HW/Espresso/Debugger/GDBBreakpoints.h
src/Cafe/HW/Espresso/Debugger/GDBStub.cpp
src/Cafe/HW/Espresso/Debugger/GDBStub.h
src/Cafe/HW/Espresso/Interpreter/PPCInterpreterImpl.cpp
src/Cafe/HW/Espresso/Interpreter/PPCInterpreterOPC.hpp
src/Cafe/OS/libs/coreinit/coreinit_Thread.cpp
src/Cafe/OS/libs/coreinit/coreinit_Thread.h
src/Cafe/OS/libs/coreinit/coreinit_ThreadQueue.cpp
src/Cafe/OS/libs/nsysnet/nsysnet.cpp
src/Common/ExceptionHandler/ExceptionHandler_win32.cpp
src/Common/precompiled.h
src/config/CemuConfig.cpp
src/config/CemuConfig.h
src/config/LaunchSettings.cpp
src/config/LaunchSettings.h
src/gui/GeneralSettings2.cpp
src/gui/GeneralSettings2.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/debugger/DebuggerWindow2.cpp
src/gui/debugger/DebuggerWindow2.h
src/gui/wxgui.h

This GDB stub allows a developer to connect existing development tools like IDA Pro, Ghidra, Clion, GDB etc. to Cemu, which allows you to set breakpoints, read and write memory and various other things in those applications. Basically provides an easier experience for reverse engineering or debugging Wii U applications if setup correctly.
This was already tested to work with IDA Pro, Clion and GDB, and seems to work pretty well. Some things I want to improve before merging:
By default this GDB stub will use port 1337. You can optionally change this in the `Options`->`General Settings`->`Debug` tab.
Then, to start a game with GDB debugging you can either use the GUI option in the `Debug`->`Launch with GDB Stub` or you can launch Cemu using the --enable-gdbstub command line option.
I think …

Add GDB stub for debugging

---

src/Cafe/HW/Espresso/Debugger/GDBBreakpoints.h

After pushing this to main we discovered that even Linux distros differ on the availability and inner workings with how ptrace works. So for now, disabling it so that main is buildable seems like the best choice until people can validate each distro and a proper solution can be found.

debugger: disable Linux read/write breakpoints for now

---

src/input/emulated/EmulatedController.cpp
src/input/emulated/EmulatedController.h

I noticed that the `EmulatedController::find_controller` method is dead code. I figure that we'd like it removed?
Here's the github search showing that it's dead code.
I've compiled this change and played around with it in the input settings screen just to confirm that nothing is broken.

Delete dead EmulatedController::find_controller method

---

src/audio/IAudioAPI.cpp
src/audio/IAudioInputAPI.cpp

This PR fixes Cemu builds with `ENABLE_CUBEB=OFF` by adding a couple of missing ifdefs. I've had to disable cubeb as it caused the build to fail on my Ubuntu 22.04/amd64 PC.

Fix building with cubeb disabled

---

src/Cafe/HW/Latte/Core/LatteShader.cpp
src/Cafe/HW/Latte/Core/LatteShader.h
src/Cafe/HW/Latte/Core/LatteShaderCache.cpp
src/Cafe/HW/Latte/Core/LatteStreamoutGPU.cpp
src/Cafe/HW/Latte/LegacyShaderDecompiler/LatteDecompiler.cpp
src/Cafe/HW/Latte/LegacyShaderDecompiler/LatteDecompiler.h
src/Cafe/HW/Latte/LegacyShaderDecompiler/LatteDecompilerAnalyzer.cpp
src/Cafe/HW/Latte/LegacyShaderDecompiler/LatteDecompilerEmitGLSL.cpp
src/Cafe/HW/Latte/LegacyShaderDecompiler/LatteDecompilerEmitGLSLHeader.hpp
src/Cafe/HW/Latte/LegacyShaderDecompiler/LatteDecompilerInternal.h
src/Cafe/HW/Latte/Renderer/RendererShader.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/RendererShaderVk.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRendererCore.cpp
src/gui/windows/TextureRelationViewer/TextureRelationWindow.cpp

`VK_KHR_SHADER_FLOAT_CONTROLS` lets us set rounding behavior for floating point math in shaders to `round-to-even` instead of truncate rounding, which more closely matches console behavior. If the extension is not supported then Cemu will fall back to default rounding.
This is a bit of a risky change since it subtly affects *all* shaders and may break things in unexpected places. For this reason I'll leave this up for a bit before merging. Testing is appreciated! But make sure to clear the shader cache first.
I'm still doing some testing myself but so far one known effect is that it fixes mobs in Minecraft having misplaced body parts:

Utilize VK_KHR_SHADER_FLOAT_CONTROLS if available

---

src/gui/GeneralSettings2.cpp
src/util/ScreenSaver/ScreenSaver.h

This option, when enabled, causes a crash in MacOS. SDL_DisableScreenSaver() requires the SDL_Video subsystem to be initialized to function properly. This causes the SDL_Events subsystem to also initialize and cause a crash elsewhere.
This PR simply disables the option box and causes the SetInhibit() function to return early.

Disable the "Disable screen saver" option in MacOS

---

src/gui/CMakeLists.txt
src/gui/CemuApp.cpp
src/gui/MainWindow.cpp
src/gui/helpers/wxWayland.cpp
src/gui/helpers/wxWayland.h

KDE requires [set_app_id](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id) to be called to display the app icon.
I don't know if there's a way to set this value in wxWidgets, in Gtk it's for each window by the [GtkApplication](https://docs.gtk.org/gio/property.Application.application-id.html)
This hack set's it directly for a Gtk window.
Currently it's only applied to the main window and the GamePad window but ideally it would run after `Show` for each toplevel window (`wxFrame`).
The `gdk_wayland_window_set_application_id` function was added in gtk `3.24.22`. Ubuntu 20.04 LTS supports `3.24.18` and with updates `3.24.20`. Therefore the function call will be dynamic.

Wayland: Set app_id for icon in kde

---

src/gui/canvas/VulkanCanvas.cpp

Use the same wayland subsurface mechanism for the GamePad window as the main window. 
Fixes this bug:
| before | after |
| - | - |
| ![Screencast from 2023-03-22 00-54-04.webm](https://user-images.githubusercontent.com/334272/226774659-075da073-f69b-44cc-b7a6-5af5b0427f21.webm) ![cemu_gamepad_before_b](https://user-images.githubusercontent.com/334272/228325688-f4481422-2e32-4a1b-b017-cdcb952a5f9a.png) ![cemu_gamepad_before_a](https://user-images.githubusercontent.com/334272/228325705-9334047c-7cd7-4b47-ab1a-ccd6ad889202.png) | ![cemu_gamepad_after](https://user-images.githubusercontent.com/334272/228325729-d4734b77-fc18-4169-a31a-2cc8ffc78238.png) |
The window decoration is shown for a single frame whenever the FPS counter is updated

Fix GamePad window when using vulkan with wayland

---

.github/workflows/build.yml

Used to get the latest version of packages. Mainly used to get the latest MoltenVK dylib
use llvm@15, llvm@16 has a compatibility issue with boost
Fixes #730

update homebrew in MacOS build action

---

dist/linux/info.cemu.Cemu.metainfo.xml

Since metainfo.xml is meant to be an AppStream file, we should follow its format recommendations. Specifically:
> A version number should always start with a number. Do not start version numbers with a letter or make them consist entirely of letters, e.g. BETA is not a version number. 
https://www.freedesktop.org/software/appstream/docs/chap-AppStream-Misc.html#spec-vercmp-recommendations

metainfo.xml: respect AppStream version format

---

dependencies/vcpkg_overlay_ports/wxwidgets/example/CMakeLists.txt
dependencies/vcpkg_overlay_ports/wxwidgets/fix-libs-export.patch
dependencies/vcpkg_overlay_ports/wxwidgets/fix-pcre2.patch
dependencies/vcpkg_overlay_ports/wxwidgets/fix_include.patch
dependencies/vcpkg_overlay_ports/wxwidgets/gtk3-link-libraries.patch
dependencies/vcpkg_overlay_ports/wxwidgets/install-layout.patch
dependencies/vcpkg_overlay_ports/wxwidgets/nanosvg-ext-depend.patch
dependencies/vcpkg_overlay_ports/wxwidgets/portfile.cmake
dependencies/vcpkg_overlay_ports/wxwidgets/relocatable-wx-config.patch
dependencies/vcpkg_overlay_ports/wxwidgets/sdl2.patch
dependencies/vcpkg_overlay_ports/wxwidgets/setup.h.in
dependencies/vcpkg_overlay_ports/wxwidgets/usage
dependencies/vcpkg_overlay_ports/wxwidgets/vcpkg-cmake-wrapper.cmake
dependencies/vcpkg_overlay_ports/wxwidgets/vcpkg.json

This changes the wxWidgets vcpkg port to no longer pull GTK from vcpkg, but instead use the system package. Basically restoring the behavior from before 3ff3b732c814abd90e40fdd95b907d183bed9ea5
This should fix #722 and also helps to avoid a new issue with GTK include files missing.

Use system GTK3 instead of vcpkg port

---

dependencies/vcpkg_overlay_ports/wxwidgets/vcpkg.json

Replicate #382 for the new wxWidgets version

Use system libpng for vcpkg on linux

---

README.md
src/gui/DownloadGraphicPacksWindow.cpp

This PR updates the URLs for the graphic pack repo to the new maintainer (cemu-project) in both the README and the hardcoded URL fallback.

Update URLs related towards cemu_graphic_packs repo.

---

src/Cafe/OS/libs/snd_core/ax_exports.cpp
src/Cafe/OS/libs/snd_core/ax_voice.cpp
src/Cafe/OS/libs/snd_user/snd_user.cpp

Converts all instances of the sndApiLog_printf() logging method with the newer cemuLog_log().
Part of #703

Logging migration (sndApiLog_printf)

---

src/Cafe/HW/Latte/Core/LatteBufferCache.cpp

I traced the red-weapon-streak bug in BotW down to a hash collision in the cache page invalidation check.
Before you could randomly get glitches like this when swinging any weapon:
When it should look like this:
I'm not 100% sure this change fixes it for good. But so far I wasn't able to reproduce anymore.

Latte: Use better hashing algorithm for cache invalidation

---

src/Cafe/OS/libs/nn_nfp/nn_nfp.cpp

Converts all instances of the `nfpLog_printf()` logging method with the newer `cemuLog_log(LogType::nn_nfp, ...)`.
Part of #703

Logging migration (nfpLog_printf)

---

src/Cafe/OS/libs/nsysnet/nsysnet.cpp

Converts all instances of the socketLog_printf() logging method with the newer cemuLog_log().
Part of #703

Logging migration (socketLog_printf)

---

src/Cafe/OS/libs/padscore/padscore.cpp
src/Cafe/OS/libs/vpad/vpad.cpp

Converts all instances of the inputLog_printf() logging method with the newer cemuLog_log().
Part of #703

Logging migration (inputLog_printf)

---

src/Cafe/OS/libs/nn_save/nn_save.cpp

Converts all instances of the `saveLog_printf()` logging method with the newer `cemuLog_log(LogType::Save, ...)`.
Part of #703

Logging migration (saveLog_printf)

---

src/Cafe/OS/libs/coreinit/coreinit_MEM.cpp
src/Cafe/OS/libs/coreinit/coreinit_MEM_ExpHeap.cpp

Converts all instances of the `coreinitMemLog_printf()` logging method with the newer `cemuLog_logDebug(LogType::CoreinitMem, ...)`.
Part of #703

Logging migration (coreinitMemLog_printf)

---

src/util/ChunkedHeap/ChunkedHeap.h

Converts one instance of `forceLog_printf ()` missed during #714
Part of #703

Converted missed forceLog_printf() log

---

src/Cafe/IOSU/legacy/iosu_fpd.cpp

The official Nintendo servers only ever return IP addresses for hosts in NEX, but real hardware is capable of resolving domains back to IP addresses. Custom servers like the ones at Pretendo Network make use of domains rather than IP addresses, which prevents Cemu from going online
These changes allow Cemu to resolve IPs from domains when connecting to the Friends NEX server
Tested on Ubuntu 22.04

Resolve domains to IPs in Friends NEX

---

src/Cafe/HW/Espresso/PPCCallback.h

Hi!
This PR fixes missing template arguments for `std::forward` call inside `PPCCoreCallback`. 
Without this trivial fix you'll get compile-time error on `PPCCoreCallback` instantiation with enum `T` and non-empty `args...` pack.  I guess there's no such usages in current code base, that's why it didn't fire yet.

Add missing template arguments for std::forward

---

CMakeLists.txt
cmake/ECMFindModuleHelpers.cmake
cmake/ECMFindModuleHelpersStub.cmake
cmake/FindWayland.cmake
cmake/FindWaylandProtocols.cmake
cmake/FindWaylandScanner.cmake
src/Cafe/CMakeLists.txt
src/gui/CMakeLists.txt
src/gui/canvas/VulkanCanvas.cpp
src/gui/helpers/wxWayland.h

This allows the compositor to scale the vulkan surface to match its parent window during resize.
| before | after |
| --- | --- |
| ![Screenshot from 2023-05-27 20-53-03](https://github.com/cemu-project/Cemu/assets/334272/7b2a5135-b89b-4d68-a3c4-424a1d64ea41) | ![Screenshot from 2023-05-27 20-58-49](https://github.com/cemu-project/Cemu/assets/334272/278fb7dd-e0ac-43e8-8be9-ad8833920d49) |
It also adds cmake modules from the kde project to generate wayland protocol headers (https://github.com/KDE/extra-cmake-modules.git)
Out of interest is there any plan to move away from wxWidgets?

Wayland: Use viewporter

---

src/Cafe/Filesystem/fsc.cpp
src/Cafe/Filesystem/fsc.h
src/Cafe/IOSU/fsa/fsa_types.h
src/Cafe/IOSU/fsa/iosu_fsa.cpp
src/Cafe/IOSU/fsa/iosu_fsa.h
src/Cafe/OS/libs/coreinit/coreinit_FS.cpp
src/Cafe/OS/libs/coreinit/coreinit_FS.h
src/Cafe/OS/libs/coreinit/coreinit_IPCBuf.cpp
src/Cafe/OS/libs/coreinit/coreinit_IPCBuf.h
src/Common/SysAllocator.h

This pull requests implements all FSA functions which are used by the FSA devoptab of [wut 1.3.0](https://github.com/devkitPro/wut) or higher.
Changes:
- [FS: add support for "a" and "a+" filemodes](https://github.com/cemu-project/Cemu/commit/4749314c91cea75fb859ccc3bb748e6987d825b2)
- [FS: Update "r+" filemode to not create non-existing files](https://github.com/cemu-project/Cemu/commit/2db76487a6614d84afdbd0d21f56a249b392c868)
- [FS: Implement support for various FSA* functions](https://github.com/cemu-project/Cemu/commit/8ccc1c04a33705a3bafa4759d9a110af58733634)
- [FS: Set FSFlag::IS_FILE flag for files to match console behaviour](https://github.com/cemu-project/Cemu/pull/844/commits/6d29c6f62a42c84a026b8f155ba1f02f2fa19712)
- [FS: Implement FSRewindDir(Async) and …

Coreinit: Implement several FSA functions and fix some bugs

---

src/gui/debugger/RegisterWindow.cpp

SetLabelText() only works for wxTextCtrl widgets on Windows.

Fix register window not updating in PPC debugger.

---

src/Cafe/IOSU/fsa/iosu_fsa.cpp
src/Cafe/OS/libs/coreinit/coreinit_FS.cpp

This PR fixes SD Access in Super Smash Bros. To fix this, two things need to be fixed:
- The FSGetMountSource implementation was simplified to return more accurate values
- Fix FSAppendFile parameters, return values and shim preparation (yes, this was totally broken before)
This PR still doesn't implement `FSAppendFile` properly, but afaik this only "reserves" space on the filesystem without actually affecting/touching the files.

FS: Fix FSGetMountSource and FSAppendFile implementation (Fixes SD access in SSBU)

---

.github/ISSUE_TEMPLATE/bug-report-feature-request.md

The FAQ link doesn't work because of trailing `/`.
The discord invites work but I still corrected them.

Fix 404 link in issue template

---

src/Cafe/OS/libs/padscore/padscore.cpp

..., and as a side effect, fixes the crash occuring due to a casting mismatch that would cause an exception within fmt when logging Input.
Closes #874

update KPADGetUnifiedWpadStatus to print ppc pointers

---

src/Cafe/CMakeLists.txt
src/Cafe/CafeSystem.cpp
src/Cafe/CafeSystem.h
src/Cafe/OS/libs/nn_act/nn_act.cpp
src/Cafe/OS/libs/nn_act/nn_act.h
src/Cafe/OS/libs/nn_olv/nn_olv.cpp
src/Cafe/OS/libs/nn_olv/nn_olv.h
src/Cafe/OS/libs/nn_olv/nn_olv_Common.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_Common.h
src/Cafe/OS/libs/nn_olv/nn_olv_DownloadCommunityTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_DownloadCommunityTypes.h
src/Cafe/OS/libs/nn_olv/nn_olv_InitializeTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_InitializeTypes.h
src/Cafe/OS/libs/nn_olv/nn_olv_UploadCommunityTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_UploadCommunityTypes.h
src/Cafe/OS/libs/nn_olv/nn_olv_UploadFavoriteTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_UploadFavoriteTypes.h
src/Cafe/TitleList/ParsedMetaXml.h
src/Cafe/TitleList/TitleInfo.cpp
src/Cafe/TitleList/TitleInfo.h
src/Cemu/napi/napi_helper.cpp
src/Cemu/napi/napi_helper.h
src/config/NetworkSettings.cpp
src/config/NetworkSettings.h

- Initialize
- Download communities (self-made / favorites / officials)
- Upload communities (create subcommunity)
- Upload favorite status (Add/Delete favorite to a subcomunity)
- This is enough for 100% support of Mario Kart 8 tournaments (considering the game server works and have tournaments enabled)
- **This was only tested on Windows** (i'm out of SSD space, getting more soon)
- The code tries to match as much as possible nn_olv.rpl behavior
- Portal app support 
- Download/Upload for posts and comments

Added base nn_olv support

---

.github/workflows/build_check.yml
src/config/CemuConfig.cpp
src/config/CemuConfig.h
src/config/LaunchSettings.cpp
src/config/LaunchSettings.h
src/gui/MainWindow.cpp
src/gui/components/wxGameList.cpp
src/gui/components/wxGameList.h

- `--title-id` parameter to allow launching a game by its title ID
- Desktop entries (Linux) / Shortcuts (Windows) can be created from the game list context menu
- Title ID column added to game list

'--title-id' parameter and desktop entry creation

---

src/gui/components/wxGameList.cpp

Linux: Save icons to user data directory, use path to AppImage as executable path in desktop entries

---

CMakeLists.txt

Related to https://github.com/cemu-project/Cemu/issues/919 and https://github.com/cemu-project/Cemu/issues/920.

cmake: exclude fmt10

---

src/gui/components/wxGameList.cpp

Quote and escape desktop entry executable path 

---

src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

When running the flatpak if the vulkan validation layer is enabled Cemu crashes with an error box that says "Error when initializing Vulkan renderer: Unable to create a Vulkan instance: -6"
](https://github.com/cemu-project/Cemu/assets/334272/0bca5db2-4d5e-447c-969c-640a48098463)
For some reason this goes away when running with the `--devel` option.
This MR adds a second attempt at creating a instance disabling all vulkan layers.
This is what [Q2RTX](https://github.com/NVIDIA/Q2RTX/blob/4f5662a7bbe70becae36b2295d956f360826ca73/src/refresh/vkpt/main.c#L892) does.
I initially tried checking against the list returned by `vkEnumerateInstanceLayerProperties` but it reports that `VK_LAYER_KHRONOS_validation` is present.

Vulkan: Retry instance creation if validation layer is not present

---

src/Cafe/HW/Espresso/Debugger/Debugger.cpp
src/Cafe/HW/Espresso/Debugger/Debugger.h
src/gui/debugger/BreakpointWindow.cpp
src/gui/debugger/BreakpointWindow.h
src/gui/debugger/DebuggerWindow2.cpp
src/gui/debugger/DisasmCtrl.cpp
src/gui/debugger/DumpCtrl.cpp
src/gui/windows/PPCThreadsViewer/DebugPPCThreadsWindow.cpp

This PR introduces logging breakpoints, something which might be helpful if you want to analyze more complex interactions in the code.  You can set these by right-clicking empty space in the breakpoint window. Some noteworthy features:
- If you give the comment a name in the breakpoint window it'll also log it so that you can more easily identify multiple logging breakpoints.
- If you enable advanced PPC debugging in the Debug->Logging menu you can also have it generate stack traces for each hit, which allows you to more easily see how the code ultimately ends up executing your code. Do note that the stack trace feature works best when Cemu is set to use interpreter mode.
Another "addition" is that the debugger will now store any breakpoints and comments across sessions. I'm not sure how …

debugger: add logging breakpoint and misc fixes

---

src/Cafe/CafeSystem.cpp

This would be useful to identifying whether a reported bug is specific to the flatpak.
I'm not sure how valid the tests for the other platforms are (AppImage).
Or whether `stat`ing `/.flatpak-info` is preferable to checking the `container` environment variable.

Log platform info

---

src/gui/input/InputSettings2.cpp
src/gui/input/settings/WiimoteControllerSettings.cpp
src/gui/input/settings/WiimoteControllerSettings.h
src/input/CMakeLists.txt
src/input/InputManager.h
src/input/api/Wiimote/hidapi/HidapiWiimote.cpp
src/input/api/Wiimote/hidapi/HidapiWiimote.h
src/input/emulated/EmulatedController.cpp

(Edit) Changes:
- Change Wiimote comparison so that controllers cannot be mistaken as others, so that using multiple Wiimotes is actually possible
- Use non-blocking reads to reduce input lag for extra Wiimotes
- Enable nunchuk motion
- Enable the Wiimote settings menu
Original Comment: 
> Now there should be no way that one controller is mistaken as being another connected controller

[Linux/MacOS] Further Wiimote changes for parity with Windows

---

src/gui/CMakeLists.txt
src/gui/MainWindow.cpp
src/gui/PairingDialog.cpp
src/gui/PairingDialog.h
src/gui/input/panels/WiimoteInputPanel.cpp
src/gui/input/panels/WiimoteInputPanel.h

figured since Cemu can directly interact with Wiimotes this would be a handy tool to have :)

Add a pairing utility for Wiimotes to Cemu

---

src/gui/GeneralSettings2.cpp

Each language name in settings will now be displayed in the respective language.
Addresses cemu-project/Cemu-Language#104

Use native language names in language setting dropdown

---

.github/workflows/generate_pot.yml
src/Cemu/Tools/DownloadManager/DownloadManager.cpp
src/gui/CemuApp.cpp
src/gui/GameProfileWindow.cpp
src/gui/GameUpdateWindow.cpp
src/gui/GeneralSettings2.cpp
src/gui/GeneralSettings2.h
src/gui/GraphicPacksWindow2.cpp
src/gui/MemorySearcherTool.cpp
src/gui/TitleManager.cpp
src/gui/components/wxDownloadManagerList.cpp
src/gui/components/wxDownloadManagerList.h
src/gui/components/wxGameList.cpp
src/gui/components/wxTitleManagerList.cpp
src/gui/components/wxTitleManagerList.h
src/gui/wxgui.h

It turns out I've been a bit too eager in replacing `.ToStdString()` with `.utf8_string()` in #956, as it caused a few strings to be displayed with broken encoding (this was particularly noticeable on Windows when using languages other than English).
The problem was due to the fact that the implicit `std::string` -> `wxString` conversion assumes that the `std::string` contains data in the current locale encoding and not in UTF-8 *(btw I have yet to understand what "current locale encoding" means, since I've observed slightly different behavior between Windows and Linux)*.
I've tried to avoid those implicit conversions as much as possible, generally by:
- returning `wxString` directly from functions when there's no point in having a `std::string`
- using `formatWxString` or a simple …

Localization fixes follow-up

---

src/Cafe/HW/Latte/Core/LatteCommandProcessor.cpp
src/Cafe/HW/Latte/Core/LatteOverlay.cpp
src/Cafe/HW/Latte/Core/LatteOverlay.h
src/Cafe/HW/Latte/Core/LattePerformanceMonitor.cpp
src/Cafe/HW/Latte/Core/LattePerformanceMonitor.h
src/Cafe/HW/Latte/Core/LatteRenderTarget.cpp
src/Cafe/HW/Latte/Core/LatteTextureReadback.cpp
src/Cafe/HW/Latte/Core/LatteTextureReadbackInfo.h
src/Cafe/HW/Latte/ISA/LatteReg.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

Changes:
- Reworked "fast drawing" logic. Fast draws are a special mode where the renderer can skip some of the more expensive per-drawcall checks if only a subset of states was changed. With this PR more drawcalls now qualify for the fast mode, reducing overall CPU load on the GPU emulation thread.
- Lowered amount of drawcalls that need to accumulate before LatteVk flushes the command buffer. Should decrease latency for texture readbacks.
- Use heuristic to determine the real resolution of colorbuffers. In cases where the aligned colorbuffer resolution mismatches the texture resolution (e.g. 1920x1088 vs 1920x1080) it is necessary to allocate and synchronize two textures. If we can guess the real colorbuffer resolution correctly we can avoid all the overhead of double textures, lowering …

Latte optimizations and tweaks

---

src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h

The render pass got created every time the swapchain is recreated (including resize). I couldn't find anywhere that actually destroys the old objects (including imgui code) so I think it just leaks. Imgui example code also seems to manually manage the render pass lifetime.

Vulkan: only create imgui render pass once

---

src/Cafe/OS/libs/nn_olv/nn_olv_PostTypes.h

Updated SetSearchKey function to handle null search keys. If a null search key is provided, the function now clears the search key at the specified index and returns success.
Fixes #973

Updated SetSearchKey function to handle null search

---

BUILD.md

These packages are needed for Fedora after this PR was merged:
https://github.com/cemu-project/Cemu/pull/950
REF: https://github.com/cemu-project/Cemu/issues/978

require libtool and libusb1-devel for Fedora

---

CODING_STYLE.md
src/audio/audioDebuggerWindow.cpp
src/config/LaunchSettings.cpp
src/gui/CemuUpdateWindow.cpp
src/gui/GeneralSettings2.cpp
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/dialogs/CreateAccount/wxCreateAccountDialog.cpp
src/gui/input/InputAPIAddWindow.cpp
src/gui/input/InputSettings2.cpp

This PR fixes some more untranslated UI strings I've stumbled upon.
While I was at it, I took the opportunity to make some minor improvements to the GUI code:
- removed all usages of the [wxT](https://docs.wxwidgets.org/3.2/group__group__funcmacro__string.html#ga437ea6ba615b75dac8603e96ec864160) macro, which is [useless since wxWidgets 3.0](https://docs.wxwidgets.org/3.2/overview_changes_since28.html#overview_changes_unicode)
- addressed a small issue in commit f6c3c96d, which mistakenly added two translatable strings containing nothing or just newlines
One last thing: I added the `wxString::FromUTF8` to the `wxString <-> std::string` conversions mentioned in the code style guidelines.
I think that it should be the preferred way to convert a `std::string` into a `wxString`. Also, …

Minor localization adjustments

---

src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h

Modify ClearColorImage to use the barrier_image template function. Also had to make a second barrier_image function that accepts VkImage which is now used by the barrier_image variant that accepts LatteTextureVk in order to avoid code duplication

Vulkan: Cleanup image barrier code

---

src/gui/CemuApp.cpp
src/gui/CemuApp.h
src/gui/GeneralSettings2.cpp
src/gui/components/wxGameList.cpp

This PR simplifies the logic for loading UI translations, which should fix several issues people have encountered.
First, we now translate UI strings using the [wxTranslations](https://docs.wxwidgets.org/3.2/classwx_translations.html) class directly: this makes language selection work with languages that aren't installed/supported on the operating system (this mostly applies to Linux: before this PR, choosing a language not installed on the machine didn't do anything).
Furthermore, the logic used to apply the UI localization has been fixed so that when the "Default" language is selected, the UI uses the system default language (and not English as it did before). The "English" language option now also works as intended: it stays selected upon closing and reopening the settings window and …

Fix several language selection issues

---

src/CMakeLists.txt
src/resource/MacOSXBundleInfo.plist.in

I've noticed in Discord that the minimum macOS version is 12 Monterey, but the actual minimum version set on the app bundle is 10.10 Yosemite. 
This PR adds the minimum version key to Info.plist, with a MACOSX_MINIMUM_SYSTEM_VERSION var. 
This var is then set to 12.0 in CmakeLists.txt
The purpose of setting the minimum version is so that users on Big Sur or lower will not be able to open the app, and they will be informed that it can't be run on their OS and they will be prompted to update. 
This should hopefully reduce the number of issues reported on GitHub and Discord. 
Testing: 
Ensure the CI builds and check that the app bundle advertises the required OS to be 12 or later.

Set macOS min version to 12.0 Monterey

---

src/CMakeLists.txt
src/resource/MacOSXBundleInfo.plist.in

Declaring support for `wua` filetypes in the info.plist will associate wua files with Cemu. 
Needs testing with the CI: 
Example from OpenEmu: 
The action we would expect is to run the `wua` on launch. 
Edit: Or else to first add to the games list and then launch...
Edit 2: Cemu opens, but nothing else happens. Functionality can be added in a separate PR.

Mac: Add wua filetype to info.plist

---

src/Cafe/CafeSystem.cpp
src/Cafe/GameProfile/GameProfile.cpp
src/Cafe/GraphicPack/GraphicPack2.cpp
src/Cafe/GraphicPack/GraphicPack2.h
src/Cafe/GraphicPack/GraphicPack2Patches.cpp
src/Cafe/GraphicPack/GraphicPack2PatchesParser.cpp
src/Cafe/HW/Latte/Core/LatteSurfaceCopy.cpp
src/Cafe/HW/Latte/Core/LatteTexture.cpp
src/Cafe/HW/Latte/LegacyShaderDecompiler/LatteDecompilerEmitGLSL.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/RendererShaderVk.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/RendererShaderVk.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/IOSU/PDM/iosu_pdm.cpp
src/Cafe/IOSU/PDM/iosu_pdm.h
src/gui/GraphicPacksWindow2.cpp

Aside from smaller refactoring and bug fixes, the bigger changes in this PR are:
- An attempt to streamline the Latte backend code for calculating slice/mip indices during texture creation and copy. There was a discrepancy where slice and mip index where calculated differently (and sometimes incorrectly) for newly created textures vs textures sourced from cache. This is a kind of risky core change that may break things, so testing is needed!
- Fixed an issue where shaders generated with [CafeGLSL](https://github.com/Exzap/CafeGLSL) could fail to compile due to using an unsupported way of encoding texture coordinates into the texture sample instruction
- Refactored unicode handling for graphic packs. Fixes #1018

Latte improvements + Better unicode support in gfx pack code

---

src/Cafe/CMakeLists.txt
src/Cafe/HW/Espresso/Debugger/GDBBreakpoints.cpp
src/Cafe/HW/Espresso/Debugger/GDBBreakpoints.h
src/Cafe/HW/Espresso/Debugger/GDBStub.cpp
src/Cafe/OS/libs/coreinit/coreinit_Thread.cpp
src/Common/ExceptionHandler/ExceptionHandler_posix.cpp

This implements support for using watchpoints with the GDBStub on linux.
Currently only tested on Arch Linux, but should be tested on other distributions as well.

GDBStub: Support watchpoints on linux

---

src/gui/canvas/VulkanCanvas.cpp

Currently if launching with a title-id Cemu stalls at the point that it tries to resize the wayland subsurface.
Fixes "Launching games directly with the --title-id argument doesn't work in Wayland" (#999)

Vulkan: Check for 0 size before wayland resize

---

src/Cafe/HW/Latte/Renderer/Vulkan/VKRPipelineInfo.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

With these changes I'm able to build against glslang 1.3.275
I think this fixes https://github.com/cemu-project/Cemu/issues/1075

Vulkan: Don't use glslang internal headers

---

src/input/api/Wiimote/hidapi/HidapiWiimote.cpp

So that it's possible to use with `SDLController`, and to prevent the controller being disconnected

Prevent Wii U Pro Controllers from being used by WiimoteControllerProvider

---

src/gui/MainWindow.cpp
src/gui/MainWindow.h

Makes the force exit key combo for various OS work when Cemu is running a game as a window or fullscreen

make altf4/cmd-q propogate to the parent after MainWindow::CreateCanvas has set focus

---

.github/workflows/build.yml
CMakeLists.txt
src/gui/CemuApp.cpp

Removes the need for a compile-time portable flag, instead supporting using either a portable or system directory at runtime.
The behavior is as follows:
* First, on all platforms, check for the directory "portable" in the same directory as the executable (or app bundle on macOS, if running from an app bundle). If that directory exists, use it for all paths.
* This is how most other emulators approach this, e.g. the Citra/Yuzu "user" directory, the Ryujinx "portable" directory, etc.
* Otherwise, match the old behavior:
* Windows: Use the directory the executable is in.
* Linux: Use XDG directories where possible, plus the other directories from wxWidgets.
* macOS: Use the standard directories from wxWidgets.

Add support for portable directory without build flag.

---

BUILD.md

The build-instructions for Ubuntu are also relevant for "Debian GNU/Linux".

BUILD.md: Mention Debian in the build-instructions for Ubuntu

---

BUILD.md

Fedora requires the llvm compiler in order to compile Cemu with `clang`. 
Installing `clang` will install `llvm-libs` but not `llvm`.
Interestingly enough it also installs `gcc` and `gcc-c++` as dependencies -- so we don't need to install those separately (if compiling with `gcc`) 
```
========================================================================================================================================
Package                                   Architecture          Version                                   Repository              Size
========================================================================================================================================
Installing:
clang                                     x86_64                17.0.6-2.fc39 …
```

add llvm package for Fedora

---

src/Cafe/OS/libs/nsyshid/BackendWindowsHID.cpp
src/Cafe/OS/libs/nsyshid/nsyshid.cpp

This should fix a nasty regression, that I introduced as part of #950, which could lead to crashes.
Sorry about that :sweat_smile:
See https://github.com/cemu-project/Cemu/pull/971#issuecomment-1813261040 and https://github.com/cemu-project/Cemu/pull/977

nsyshid: remove stray print statements

---

src/Cafe/CafeSystem.cpp

Fixes: #911
This makes sure that the gameprofile is loaded when the recompiler initialises and uses the selected mode.

CafeSystem: call PPCRecompiler_init after SetupExecutable

---

src/Common/ExceptionHandler/ExceptionHandler_posix.cpp

Addresses one concern of #1013
The issue also points out that linux (or at least utilities like killall) look(s) at the thread name and not the executable name.
We could change the name of the main thread to something ``cemu`` on linux. Which seems sensible because threads that don't set their name inherit the name of the thread that created them. So many Cemu threads are now called MainThread, which also isn't very helpful. But that's for another PR I think.

Linux: Exit on SIGTERM

---

src/Cafe/CafeSystem.cpp

#1115 introduced a crash when the game profile was set to anything other than single-core interpreter.
Instead of shuffling the init order, move call to load the game profile.

Fix crash instroduced by #1115

---

src/Cafe/HW/Espresso/Debugger/GDBStub.cpp
src/Cafe/HW/Espresso/Recompiler/PPCRecompiler.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/RendererShaderVk.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanPipelineStableCache.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRendererCore.cpp
src/Cafe/IOSU/ODM/iosu_odm.cpp
src/Cafe/IOSU/PDM/iosu_pdm.cpp
src/Cafe/IOSU/nn/iosu_nn_service.cpp
src/Cafe/OS/libs/coreinit/coreinit_Thread.cpp
src/Cafe/TitleList/SaveList.cpp
src/Cafe/TitleList/TitleList.cpp
src/Cemu/FileCache/FileCache.cpp
src/gui/components/wxGameList.cpp
src/gui/guiWrapper.cpp
src/input/InputManager.cpp
src/input/api/DSU/DSUControllerProvider.cpp
src/input/api/SDL/SDLControllerProvider.cpp
src/input/api/Wiimote/WiimoteControllerProvider.cpp
src/util/helpers/helpers.cpp

Fixes #1013
I set out to change the main thread name to `cemu` like I suggested in #1116 and in the process I discovered that many threads did not get their proper names on Linux. The man page for `pthread_setname_np` states: `The thread name  is  a  meaningful  C  language string, whose length is restricted to 16 characters, including the terminating  null  byte  ('\0').` This means that there are only 15 usable characters. Instead of cutting them off at 15 characters I decided to find shorter names. I opted to change the names for all platforms because having preprocessor macros would make things needlessly cluttered. I also discovered some nameless threads and named them.
The `killall cemu` command now works as expected.
Before patch             |  After patch …

Update thread names

---

src/Cafe/HW/Latte/LegacyShaderDecompiler/LatteDecompilerEmitGLSL.cpp
src/Cafe/HW/Latte/Renderer/OpenGL/OpenGLRenderer.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h
src/input/motion/MotionSample.h

These are some minor changes I collected over many months.
Since these are very small I didn't want to open a pull request for them individually. But I guess it's time for some spring cleaning :wink: 
In order from most to least significant:
- Remove a semaphore and replace it with std::atomic_flag
- Fix a fmt::format format string
- Delete an unusused and unimplemented function declaration
- Convert a file to UTF-8

Minor changes

---

src/gui/input/InputSettings2.cpp
src/gui/input/InputSettings2.h

get_emulated_controller_types always returned zero for the number of wpads. It _was_ able to count VPAD's because EmulatedController::VPAD is the only enum value that evaluates to false.
Additionally, create all pages of the input settings menu when it is first opened, so that the counter can see controllers on different pages before the user viewed those pages.
This restores the WPAD limit of 7.

InputSettings: Fix controller type counter to restore WPAD limit

---

src/Cafe/HW/Latte/Renderer/Vulkan/SwapchainInfoVk.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/SwapchainInfoVk.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h

* make surfaces entirely managed by SwapchainInfoVK (and actually destroy the surfaces in destructor)
* destroy temporary surface for device enumeration
* simplify SwapchainInfoVk constructor
* change drawbackbuffer render pass load operation to OP_LOAD, so that when the swapchain image was cleared the black background is kept (formally, it always was in practice)
* fix structure type enum
* move queue family code back into VulkanRenderer

Vulkan: several fixes and refactors

---

src/Cafe/TitleList/ParsedMetaXml.h
src/Cafe/TitleList/TitleInfo.cpp
src/gui/CemuApp.cpp
src/gui/components/wxGameList.cpp

- Windows icons are stored as `.ico` files to `%LOCALAPPDATA%/Cemu/icons/`
- Long title names chosen as some games (NSMBU + NSLU) add trailing dots for their shortnames
- Long title names have their newlines replaced with spaces at parsing
- Linux shortcut paths are saved with UTF-8 encoding
- Game titles are copied and saved with UTF-8 encoding

Changes to game shortcuts and UTF8 gamelist name fixes

---

src/resource/MacOSXBundleInfo.plist.in

This PR adds all languages which have an available UI translation in Cemu to the macOS property list as recommended by [wxWidgets docs](https://docs.wxwidgets.org/3.2/overview_i18n.html).
This should allow macOS to recognize that the application supports a specific language and therefore translate system-provided menus accordingly (e.g. the "Windows" one).
Previously, macOS-provided menus were always displayed in English. After this change, they should always appear in the system language, if it's among the languages listed in the `CFBundleLocalizations` array.
Should fix the issue reported in https://github.com/cemu-project/Cemu/issues/735#issuecomment-2006455073 _(EDIT: it seems to mitigate the issue but doesn't solve it completely)_
Testing by non-English macOS users is appreciated.

Add supported localizations to macOS plist

---

src/config/CemuConfig.cpp
src/config/CemuConfig.h
src/gui/components/wxGameList.cpp
src/gui/components/wxGameList.h

Remove the icon column and display the icon in the name column.
Before:
After:

UI: add option to hide the icon column

---

src/Cafe/OS/libs/coreinit/coreinit_Thread.cpp

On linux cemu sometimes randomly crashes on startup. Looking at the coredump in a debugger showed that it crashed in emplace_back for a vector because of a double free. Write access to a vector is not thread-safe, but when cemu is in multi-core recompiler mode when the timing is just right two or more threads simultaneously emplace in the vector. Added a mutex to protect access.

coreinit: fix race condition that causes crash

---

src/gui/DownloadGraphicPacksWindow.cpp
src/gui/GraphicPacksWindow2.cpp
src/gui/GraphicPacksWindow2.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h

Constructing DownloadGraphicPacksWindow launches a thread to run the graphic packs update tasks on. When a game is running the thread instead calls wxMessageBox to display an error and immediately returns. On windows this likely uses the system's MessageBox functions, which I believe spawn a window controlled by some system-level process meaning the application only has to read the result. However linux doesn't have native messagebox functionality like that and in order for an application to display any kind of window it has to manage it's event loop. For whatever reason wxMessageBox in the update thread gets stuck and the messagebox cannot be closed. The debugger shows that both the main UI thread and the graphic pack update thread are running a GTK event loop, either waiting for a …

GraphicPacksWindow2: Disable update button when a game is running

---

src/Cafe/HW/Espresso/Debugger/DebugSymbolStorage.h

This fixes a bug where ClearRange goes into an infinite loop when length is not divisible by 4. Because length is unsigned it wraps around to UINT32_MAX and never becomes zero. Because of this bug, if a user disables a graphic pack like "Graphics" for botw while the game is running length is equal to 9 and the UI thread freezes and never recovers.

DebugSymbolStorage: fix infinite loop

---

src/Cafe/OS/RPL/elf.cpp

This fixes crashing when homebrew applications are started from an ELF file with the recompiler enabled.

ELF loader: allocate PPC-recompiler jump table for executable sections

---

src/Cafe/IOSU/legacy/iosu_fpd.cpp
src/Cafe/IOSU/legacy/iosu_fpd.h
src/Cemu/nex/nexFriends.cpp
src/Cemu/nex/nexFriends.h

iosu_fpd.cpp, nexFriends.cpp and nexFriends.h are edited to have these changes:
- Starting a friend session on a non-game application (system app, etc) will force myPresence.gameKey.titleId and myPresence.gameKey.ukn to be 0 in order to avoid the app from showing up as "???" for other people in Friend List and instead have no icon just like in real hardware
- Updating the gamemode will force myPresence.gameKey.titleId and myPresence.gameKey.ukn to be the current foreground title id/version (or 0 if not a game app) in order to avoid the app from showing up as "???" for other people in Friend List (the titleid is incorrect when the gamemode is updated, not sure why)
- Renamed nexFriend->gameModeMessage to nexFriend->comment since it is the status comment of an account, nothing to do with …

Avoid current app from showing up as "???" for others in Friend List + View friends' status

---

src/Cafe/HW/Latte/Core/LatteRenderTarget.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/SwapchainInfoVk.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/SwapchainInfoVk.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h

Removing PreparePresentationFrame:
PreparePresentationFrame was a hacky workaround because the VulkanRenderer did not adhere to the same interface as the OpenGL renderer. It became redundant at some point during the swapchain refactors. Everything acquires it's own image or reuses a previously acquired image now so there's no need to depart from the generic interface anymore.
Removing the fence:
I was reading [this article from 2022](https://www.collabora.com/news-and-blog/blog/2022/06/09/bridging-the-synchronization-gap-on-linux/) where at some point it mentions that on Intel ANV ``we run into problems when implementing vkWaitForFences() for the fence from vkAcquireNextImageKHR(). That has to be done via DRM_IOCTL_I915_GEM_WAIT which can't tell the difference between the compositor's …

Vulkan: remove present fence and PreparePresentationFrame

---

dist/linux/appimage.sh

As it turns out fixing the symbols in the debug output for AppImage builds was very simple.
Linux deploy strips binaries by default. They helpfully provide the ``NO_STRIP`` environment variable to not strip...
https://github.com/linuxdeploy/linuxdeploy/issues/72
``NO_STRIP`` not set:
``NO_STRIP`` set to 1:

CI: Don't strip AppImage symbols

---

src/Cafe/HW/Latte/Renderer/OpenGL/OpenGLRenderer.cpp

This fixes a crash when GL_VERSION is null for any reason. For instance when OpenGL fails to initialize.

fix a crash when GL_VERSION is null

---

src/Cafe/OS/libs/nsysnet/nsysnet.cpp

This PR changes the following:
- Adds missing WU sockopt types
- Avoids always raising an assert for unimplemented types
- Properly handle `NULL` `src_addr` and `addrlen` in `recvfrom`
- Implements `getsockopt` with `SO_TYPE` to query the socket type

nsysnet: Some improvements

---

src/input/api/Controller.h
src/input/api/ControllerState.h
src/input/api/DSU/DSUController.cpp
src/input/api/DSU/DSUController.h
src/input/api/Wiimote/NativeWiimoteController.cpp
src/input/api/Wiimote/NativeWiimoteController.h
src/input/api/Wiimote/WiimoteControllerProvider.cpp
src/input/api/Wiimote/WiimoteControllerProvider.h
src/input/emulated/EmulatedController.cpp
src/input/emulated/EmulatedController.h
src/input/emulated/WPADController.cpp

`dpd_valid_fg` was  (and probably still is) reported incorrectly. 
From testing on my own Wii U, I observed:
- `1` is hard to get consistently
- `2` is returned when aiming normally
- `-1` when only one IR cluster is visible
-  `0`  when not aiming at the sensor bar at all and IR position values no longer change
I haven't tested in any games on Cemu (my Wiimotes refuse to connect to my PC).
Hopefully other people can test it.

Improve setting of dpd_enable_fg

---

src/Cafe/OS/libs/nn_act/nn_act.cpp

This implements `nn::act::GetTransferableId` (the non-Ex version of `nn::act::GetTransferableIdEx`).
Pokemon Rumble U uses this to store the coin count for the current account in the common save.

nn_act: Implement GetTransferableId

---

src/Cemu/PPCAssembler/ppcAssembler.cpp

This patch should fix the issue I described in #1200.

Fix commas edge case in strings when parsing an assembly line

---

src/Cafe/TitleList/TitleId.h

This is primarily to silence this log output when WUHB homebrew applications are in the game path.

TitleID: add homebrew title type

---

src/Cafe/HW/Latte/Renderer/OpenGL/RendererShaderGL.cpp

The code that uses glProgramBinary to load compiled shaders from shaderCache/precompiled/\<TitleID\>_gl.bin files is unreachable. The fileSize variable is never changed so the function always fails. This means Cemu has been relying entirely on driver cache implementations for some time. (they must be pretty effective since nobody seems to have noticed this)

OpenGL: fix loading cached shaders from GL cache files

---

src/CMakeLists.txt

Sets the absolute path to the library and changes the binary to search the Frameworks path of the bundle.
Fixes https://github.com/cemu-project/Cemu/issues/1214

set VCPKG path to libusb for MacOS

---

src/gui/PadViewFrame.cpp

The gamepad window was the wrong size.
I don't know wxWidgets well enough to say why this fix works or whether it will cause issues.
| before | after |
|-|-|
| ![Screenshot from 2024-05-27 11-34-59](https://github.com/cemu-project/Cemu/assets/334272/c9cf4a50-6595-48dc-ad44-2962143cdd84) | ![Screenshot from 2024-05-27 11-33-21](https://github.com/cemu-project/Cemu/assets/334272/57a12340-00df-46b6-92d2-8ea1ca85e52c) |

Fix GamePad window size

---

src/Cafe/CMakeLists.txt
src/Cafe/OS/libs/nsyshid/AttachDefaultBackends.cpp
src/Cafe/OS/libs/nsyshid/Backend.h
src/Cafe/OS/libs/nsyshid/BackendEmulated.cpp
src/Cafe/OS/libs/nsyshid/BackendEmulated.h
src/Cafe/OS/libs/nsyshid/BackendLibusb.cpp
src/Cafe/OS/libs/nsyshid/BackendLibusb.h
src/Cafe/OS/libs/nsyshid/BackendWindowsHID.cpp
src/Cafe/OS/libs/nsyshid/BackendWindowsHID.h
src/Cafe/OS/libs/nsyshid/Skylander.cpp
src/Cafe/OS/libs/nsyshid/Skylander.h
src/Cafe/OS/libs/nsyshid/nsyshid.cpp
src/config/CemuConfig.cpp
src/config/CemuConfig.h
src/gui/CMakeLists.txt
src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.cpp
src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h

Carrying on from some of the work I have done on Dolphin and RPCS3, and thanks to https://github.com/cemu-project/Cemu/pull/950 being merged, I am opening this PR up with the ability to emulate the Skylander Portal on Cemu.
Currently have tested Trap Team and Swap Force as working on my Mac, but hoping to get feedback and some testers on this PR too. Hoping to add Disney Infinity in the near future, but I don't currently have access to my Wii U so can't dump the necessary erreula to test my changes have actually worked there.
Would partly close https://github.com/cemu-project/Cemu/issues/588

nsyshid: Emulate Skylander Portal

---

src/gui/PadViewFrame.cpp

Don't change the size on canvas initialization
This fixes the issue mentioned in response to #1224 that the GamePad window cannot be shrunk bellow 854x480.

Create GamePad window at correct size

---

src/resource/embedded/fontawesome.S

I've started to actually learn how the GNU assembler/linker work. No idea why I thought it was a good idea at the time to put a font in the .text segment. Fontawesome does _not_ need to execute :sweat_smile:

resource: move fontawesome to .rodata

---

src/Cafe/CMakeLists.txt
src/Cafe/OS/libs/nsyshid/BackendEmulated.cpp
src/Cafe/OS/libs/nsyshid/Infinity.cpp
src/Cafe/OS/libs/nsyshid/Infinity.h
src/Cafe/OS/libs/nsyshid/Skylander.cpp
src/Cafe/OS/libs/nsyshid/Skylander.h
src/config/CemuConfig.cpp
src/config/CemuConfig.h
src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.cpp
src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.h

Following on from https://github.com/cemu-project/Cemu/pull/971, I am bringing the emulated Infinity Base that I created for Dolphin and RPCS3 here to Cemu. Currently the games all require the erreula.rpl and title files for erreula to launch, and will error if the files required for online play aren't present either. I have tested launching in to 1.0 successfully on my Mac, however because of the issues with Geometry Shader Conversion I am unable to actually play the games, but I am actively testing on my Windows machine everything works as expected there too. Will partly close https://github.com/cemu-project/Cemu/issues/588

nsyshid: Emulate Infinity Base

---

BUILD.md

As of Fedora 40, `zlib-devel` no longer provides the required zlib static library at `/usr/lib64/libz.a`.

Update Fedora build instructions [skip ci]

---

src/Cafe/CMakeLists.txt
src/Cafe/OS/libs/coreinit/coreinit_SysHeap.cpp
src/Cafe/OS/libs/coreinit/coreinit_SysHeap.h
src/Cafe/OS/libs/h264_avc/H264Dec.cpp
src/Cafe/OS/libs/h264_avc/H264DecBackendAVC.cpp
src/Cafe/OS/libs/h264_avc/H264DecInternal.h
src/Cafe/OS/libs/h264_avc/parser/H264Parser.cpp
src/Cafe/OS/libs/h264_avc/parser/H264Parser.h

By design `h264.rpl` exposes only a synchronous API where decoding only happens during `H264DECExecute` calls. However, if H264DEC runs in buffered mode we can use asynchronous decoding under the hood while still simulating a synchronous API on top of it. In most cases this lets us hide the latency of our software decoder which helps with games that are picky about decoding times.
Should help with #217
Marking this as draft for now since I still have to go through all the games with videos to make sure there are no regressions.

h264: Use asynchronous decoding when possible

---

src/Cafe/OS/libs/nsyshid/Skylander.cpp
src/Cafe/OS/libs/nsyshid/Skylander.h
src/config/CemuConfig.h
src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.cpp

A user on Discord reported that Skylanders wasn't working in the latest releases - I found that the code that I changed to represent the Skylander File Sizes was incorrectly used, and the game would only read the first 16 bytes of the Skylander file in to the game, which caused issues when trying to load figures in to the game, causing an error to appear saying that there is an issue with the Skylander toy. Also have done some formatting to a couple of classes, and made the default for the emulated infinity base setting to be default, so users will need to turn this on again if they want to use this feature - users who have used the last few releases will have had this enabled by default.

nsyshid: Tidyups and Fixes

---

.github/workflows/build.yml

do not manually install python, it comes preinstalled on the GH runner and updating it through brew is broken

CI: fix macOS build

---

src/Cafe/Filesystem/FST/fstUtil.h
src/Cafe/Filesystem/fsc.h
src/Cafe/Filesystem/fscDeviceRedirect.cpp
src/Cafe/GraphicPack/GraphicPack2.cpp

Allows games to see new files in graphics packs when iterating directories.
Example: Bayonetta 2, when you patch its code to load files outside CPKs, uses directory iterate functions to find files. This change allows it to find files in graphics packs.

Add support for iterating directories in graphics pack content folders.

---

dist/linux/appimage.sh

Add [checkrt](https://github.com/darealshinji/linuxdeploy-plugin-checkrt) plugin in order to detect the correct `libstdc++.so.6` version at runtime. The current method of bundling `libstdc++.so.6` is wrong and may cause conflicts ([1](https://discourse.appimage.org/t/im-a-big-fan-of-this-but-graphics-driver-libstdc-conflict/171/3), [2](https://github.com/cemu-project/Cemu/issues/1280)) if the base system contains fresh packages.  For context, this is the [recommended](https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#libstdcso6) way to do this.

Update appimage.sh to support runtime libstdc++.so.6 loading

---

src/Cafe/IOSU/legacy/iosu_fpd.cpp
src/Cafe/IOSU/legacy/iosu_fpd.h
src/Cafe/OS/libs/nn_fp/nn_fp.cpp
src/Cemu/nex/nexFriends.cpp
src/Cemu/nex/nexFriends.h

- When starting a friend session, myComment (nexComment) will be stored in the session (NexFriends) variable
- Using GetMyComment will then get session->myComment and convert the commentString to UTF16
- Implemented nexComment.writeData
- UpdateCommentAsync and UpdatePreferenceAsync are incredibly similiar to each other, so most of the code is copied over from that in order to make it work

nn_fp: Implement GetMyComment and UpdateCommentAsync

---

.github/workflows/build.yml
BUILD.md
CMakeLists.txt
dependencies/ih264d/CMakeLists.txt
src/asm/CMakeLists.txt

This implements and utilizes better support for cross-compiling on ARM macOS.
On the build side:
* Fixes architecture detection for ih264d and CemuAsm by using the value of `CMAKE_OSX_ARCHITECTURES` when available. Also added support for detecting the `arm64` value used on Mac while I was there for future ARM support.
* Sets `CMAKE_OSX_DEPLOYMENT_TARGET` to the minimum supported OS version to make sure the output executable has the correct support.
* Updates build instructions:
* An x86_64 shell is no longer necessary for cross-compiling; it works fine as long as you pass the right architecture to CMake and install x86_64 versions of MoltenVK and Boost. I split up the dependencies section into tools and libraries, put instructions for installing x86_64 libraries from Homebrew, and removed …

build: Better support for cross-compiling on ARM macOS.

---

dist/linux/appimage.sh

This is supposed to be handled by checkrt now, but if the library is available in `usr/lib/` in the AppImage, it will be loaded from there instead.
Fixes https://github.com/cemu-project/Cemu/pull/1292

appimage.sh: Do not copy `libstdc++.so.6` to `usr/lib/`

---

src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRendererCore.cpp

Check if the uniform ringbuffer is full and if it is wait for commands to finish.
In my testing Breath of the Wild can run correctly with a ring buffer as small as 10 KB (with terrible performance obviously). When using a buffer smaller than that debug builds can detect corruption and assert/log. Although it's definitely impossible above a certain ringbuffer size.

Vulkan: Protect against uniform var ringbuffer overflow

---

src/Cafe/CafeSystem.cpp
src/Cafe/HW/Latte/Core/Latte.h
src/Cafe/HW/Latte/Core/LatteRenderTarget.cpp
src/gui/input/panels/VPADInputPanel.cpp
src/gui/input/panels/VPADInputPanel.h
src/input/emulated/VPADController.cpp
src/input/emulated/VPADController.h

In addition to adding a checkbox this also alters the behaviour of pressing the "show screen" button. Currently if you enable the "Launch with gamepad view" option in the game profile, pressing the button does nothing. I've changed it so it acts like the TAB key and shows the TV screen.
I'm not happy with the alignment of the volume slider and the checkbox. That's the main reason why this is marked as draft. I think it needs to look a little more polished.
EDIT: I've added a windows screenshot since writing this and I think it doesn't look as bad on windows.
Closes: #1373
Closes: #916

Add toggle button to VPAD show screen input

---

src/gui/input/InputAPIAddWindow.cpp
src/gui/input/InputAPIAddWindow.h

input: Fix crash when closing add controller dialog before search completes

---

src/CMakeLists.txt

The path to libusb dylib was hardcoded to match the one used by GitHub actions when creating a macOS bundle. This PR uses a relative path instead and supports debug build path as well.

macOS: Fix libusb path for bundle

---

src/Cafe/OS/libs/proc_ui/proc_ui.cpp

ProcUI: swap `tickDelay` and `priority` args in callbacks

---

src/Cafe/OS/libs/nsyshid/BackendLibusb.cpp

nsyshid/libusb: correct error message formatting, and print error string on open fail

---

src/Cafe/CMakeLists.txt
src/Cafe/OS/libs/nsyshid/BackendEmulated.cpp
src/Cafe/OS/libs/nsyshid/Dimensions.cpp
src/Cafe/OS/libs/nsyshid/Dimensions.h
src/config/CemuConfig.cpp
src/config/CemuConfig.h
src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.cpp
src/gui/EmulatedUSBDevices/EmulatedUSBDeviceFrame.h

This PR aims to emulate the last mainstream toys-to-life peripheral, the Lego Dimensions Toypad. The Toypad is functionally very similar to the Disney Infinity Base, it has 2 endpoints, one for reading and one for writing, and all requests and responses are padded to 32 bytes.
The UI I have created functions mostly the same as the Skylander Portal and Infinity Base, but the layout is slightly different, to try to match the positions of a physical portal:
Users can Clear minifgures from the UI, Create either a new Character, or a 'Blank Tag' which can be used to store gadgets from the game, or Load an existing dump.
The game quite frequently requires figures to be moved to different positions on the Toypad, so I have added in a move button, which opens up a new UI window allowing users to …

nsyshid: Emulate Dimensions Toypad

---

src/Cafe/GraphicPack/GraphicPack2.cpp
src/Cafe/HW/Latte/Core/LatteRenderTarget.cpp
src/Cafe/HW/Latte/Renderer/OpenGL/OpenGLRenderer.cpp
src/Cafe/HW/Latte/Renderer/RendererOuputShader.cpp
src/Cafe/HW/Latte/Renderer/RendererOuputShader.h
src/Cafe/HW/Latte/Renderer/Vulkan/LatteTextureViewVk.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp

Make built-in scaling shaders compatible with vulkan and incorporate the fixes from #879
- Cemu now prepends a preamble containing all the uniforms so you can just write the shader parts :smile: 
- preamble uses GLSL version 430
- ``textureSrcResolution`` is now the actual resolution of the textureSrc sampler.
- ``inputResolution`` has been replaced by ``nativeResolution`` and gives the resolution that the game would render at without graphic pack overrides.
https://github.com/cemu-project/Cemu/blob/e2e9e81c3eaa626b401a9a61f10daf7335f95d7f/src/Cafe/HW/Latte/Renderer/RendererOuputShader.cpp#L287-L302

Vulkan: Make scaling shaders compatible + fixes

---

src/Cafe/CMakeLists.txt

Cafe: Fix linker failure with glslang 15.0.0

---

CMakeLists.txt
src/gui/CMakeLists.txt
src/gui/CemuApp.cpp

`ALLOW_PORTABLE` cmake flag to determine whether portable mode *can* be used. Defaulted to `ON`.
Also check that the portable path is indeed a directory, as in https://github.com/cemu-project/Cemu/pull/1445
Fixes https://github.com/cemu-project/Cemu/issues/1444

ALLOW_PORTABLE build flag and directory check 

---

src/Cafe/CafeSystem.cpp
src/Cafe/HW/Espresso/Debugger/Debugger.cpp

Cemu's CPU interpreter mode (as opposed to the default speedy recompiler mode) is expected to be primarily used for debugging, and thus should always be used with one core. However, unlike the game profile option, the `--force-interpreter` launch parameter didn't limit the amount of cores used to 1 which caused issues with multiple threads trying to be paused at the same time.
This commit fixes that issue, alongside an additional fix that might help situations where a debugger trap instruction gets hit by two threads simultaneously. Eventually this should be replaced with a more advanced approach that'd freeze other threads while stepping.

Always use a single core while interpreter mode

---

BUILD.md

Changed bluez-libs to bluez-libs-devel and added wayland-protocols-devel on fedora dependencies command.
Added troubleshooting step for alternative architectures as required by vcpkg, found when building on a M1 macbook air running fedora asahi remix.

Updated dependencies for fedora, added troubleshooting flag for alternative architectures

---

src/Cafe/HW/Latte/Renderer/Vulkan/TextureReadbackVk.cpp

Tentative fixes, i could not verify as i don't own the games, for #1296 and #1305 .
Can you please test @Triticum0

Readback Vulkan fixes

---

src/Cafe/HW/Latte/Core/LatteCommandProcessor.cpp
src/Cafe/HW/Latte/Core/LatteIndices.cpp
src/Cafe/HW/Latte/Core/LatteIndices.h
src/Cafe/HW/Latte/Core/LatteOverlay.cpp
src/Cafe/HW/Latte/Core/LattePerformanceMonitor.cpp
src/Cafe/HW/Latte/Core/LattePerformanceMonitor.h
src/Cafe/HW/Latte/Core/LatteRenderTarget.cpp
src/Cafe/HW/Latte/Renderer/OpenGL/OpenGLRenderer.h
src/Cafe/HW/Latte/Renderer/Renderer.h
src/Cafe/HW/Latte/Renderer/Vulkan/VKRMemoryManager.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VKRMemoryManager.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h
src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRendererCore.cpp
src/Common/precompiled.h
src/util/ChunkedHeap/ChunkedHeap.h

What this PR does:
- Implement a 8-entry LRU cache for indices, instead of only remembering the indices from the previous draw
- Reworked the `indexData_*` renderer interface a bit and added `indexData_releaseIndexMemory` to let the renderer know when cached index data won't be referenced anymore
- Implement this new interface on Vulkan. OpenGL uses a custom index cache so it's not affected
While working on this I realized that it's probably possible to share the buffer and heap allocator part of the logic between all three backends, so that the individual renderers would only have to implement buffer creation and uploads. But let that be a problem for the future.

Implement better index caching in Latte

---

src/Cafe/OS/libs/nsyshid/BackendLibusb.cpp

As the SetReport method now uses a reference to m_interfaceIndex when sending reports, this needs to be initialised as 0 as initialising as 1 causes errors if a device has only 1 interface (which is all USB portals that I know of). Should have been included as part of https://github.com/cemu-project/Cemu/pull/1471

nsyshid: Initialise libusb index as 0

---

src/Cafe/GameProfile/GameProfile.cpp

I don't know why this particular enum is not deal with [this code](https://github.com/cemu-project/Cemu/blob/eab1b24320454ef60d6172dd41dfa8379b3015ac/src/Common/precompiled.h#L566-L577), but it solve this error since [fmt 11.1.0](https://github.com/fmtlib/fmt/releases/tag/11.1.0):
```
[505/518] Building CXX object src/Cafe/CMakeFiles/CemuCafe.dir/Account/Account.cpp.o
samu: job failed: /usr/lib/ccache/bin/c++ -DBOOST_NOWIDE_DYN_LINK -DBOOST_NOWIDE_NO_LIB -DEMULATOR_HASH=eab1b243 -DEMULATOR_VERSION_MAJOR=0 -DEMULATOR_VERSION_MINOR=0 -DEMULATOR_VERSION_PATCH=0 -DENABLE_DISCORD_RPC -DENABLE_FERAL_GAMEMODE -DFMT_SHARED -DHAS_BLUEZ -DHAS_CUBEB=1 -DHAS_HIDAPI -DHAS_WAYLAND -DSUPPORTS_WIIMOTE -DVK_NO_PROTOTYPES -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR …
```

Fix building against fmt 11.1.0

---

src/gui/MainWindow.cpp

Especially helpful for non-portable Linux users, who have `shaderCache` outside of the main Cemu directory

gui: Add menu item for opening shader cache directory

---

src/Cafe/HW/Espresso/Debugger/Debugger.cpp
src/Cafe/HW/Espresso/Debugger/Debugger.h
src/gui/debugger/BreakpointWindow.cpp
src/gui/debugger/DisasmCtrl.cpp
src/gui/debugger/DisasmCtrl.h

Like the title describes, this allows a savy user, developer or modder to change the comment field of a logging breakpoint to include placeholders such as {r3} or {f3} to log the register values whenever that code is hit.

debugger: allow printing registers using logging breakpoint placeholders

---

src/gui/TitleManager.cpp
src/gui/components/wxGameList.cpp
src/gui/components/wxTitleManagerList.cpp

On macOS, trying to open save directory locations through the context menu usually results in errors like:
```
Failed to open URL "file:/Users/xxxxx/Library/Application Support/Cemu/mlc01/usr/save/00050000/xxxxxxxx" in default browser. (error 0: Undefined error: 0)
```
This is due to the default MLC path on macOS being located at `~/Library/Application\ Support/Cemu/mlc01`, which contains a space. I tried escaping with a `\` or surrounding the path with `""`, but it appears that since `wxLaunchDefaultBrowser` is being used then URI encoding is required. ~I couldn't find a URI encoding function in either `<wx/uri.h>` or `<wx/url.h>`, so I just did a manual string replacement of all spaces.~
~Alternatively,~ it's possible to just use `wxLaunchDefaultApplication` instead like this: …

Fix opening of save directory on macOS

---

src/Cafe/CafeSystem.cpp
src/Cafe/HW/Espresso/Recompiler/PPCRecompiler.cpp
src/config/LaunchSettings.cpp
src/config/LaunchSettings.h

This option still allows you to have proper stack traces for crashes or for the PPC debugger, but is a lot faster then the really slow interpreter (especially when loading into large games like BotW where there has to be a lot of asset decompressing). It makes memory access breakpoints much more brittle though, so it's not a perfect option.
Normal users should of course stick with using the recompiler.

debug: add CLI option to have multithreaded interpreter

---

.gitmodules
CMakeLists.txt
src/Cafe/CMakeLists.txt
src/Cafe/HW/Espresso/Recompiler/BackendAArch64/BackendAArch64.cpp
src/Cafe/HW/Espresso/Recompiler/BackendAArch64/BackendAArch64.h
src/Cafe/HW/Espresso/Recompiler/IML/IMLOptimizer.cpp
src/Cafe/HW/Espresso/Recompiler/IML/IMLRegisterAllocator.cpp
src/Cafe/HW/Espresso/Recompiler/PPCRecompiler.cpp

This PR adds a recompiler backend for the AArch64 architecture.
The backend uses a third-party library for emitting AArch64 code ([xbyak_aarch64](https://github.com/fujitsu/xbyak_aarch64)).

Add AArch64 recompiler backend

---

src/util/helpers/StringHelpers.h

Fix for the build issue reported in #1547 
Xcode 16.3 removed the base template for `std::char_traits`: https://developer.apple.com/documentation/xcode-release-notes/xcode-16_3-release-notes. As a result, the `basic_string<uint16be>` type in this code gives compiler errors, as the `basic_string` template relies on `char_traits`:
https://github.com/cemu-project/Cemu/blob/e6a64aadda4d99ebe16f33f55b0a813444827a06/src/util/helpers/StringHelpers.h#L28-L35
I implemented the removed template for the `uint16be` type based on the documentation found in `Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__string/char_traits.h`
With this, I was able to build the macOS app bundle and launch games successfully. However, the standalone `Cemu_release` executable (without the app …

Fix Mac build for Xcode 16.3

---

src/Cafe/OS/libs/nsyshid/Whitelist.cpp

Allows users to play Kamen Rider: Summon Ride on Cemu with their USB Portal from the PS3 or Wii U version of the game

nsyshid: Add Kamen Rider USB Device to Whitelist

---

src/Cafe/OS/libs/dmae/dmae.cpp

Simply adapted from the 32bit behavior above.
Needed it for an homebrew app.

dmae: Implement 16bit endian swap for DMAECopyMem

---

.github/workflows/build.yml

This bumps the MVK version to 1.3.0 in the CI. 
Not sure if this is the only place it needs to be changed, but I wasn't able to find another reference to it. 
MVK 1.3.0 adds full Vulkan 1.3 support and many bug fixes.
Full changelog is [here](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.3.0).

CI: Bump MoltenVK to v1.3.0

---

src/gui/MainWindow.cpp

This PR updates the `MainWindow::OnKeyDown` logic to prevent `Ctrl+Q` from closing the application on Windows and Linux.
On non-macOS platforms, `Ctrl+Q` is not a standard quit shortcut. However, it was previously hardcoded in Cemu to close the window, using `event.CmdDown() && event.GetKeyCode() == 'Q'`, which maps to `Ctrl+Q` on Windows/Linux and `Cmd+Q` on macOS.
For users who map `Ctrl+Q` (or press it accidentally) during gameplay—especially those playing with keyboard controls—this could result in an unexpected app exit and potential progress loss.
- The quit shortcut `Cmd+Q` now works **only** on macOS.
- On Windows/Linux, only `Alt+F4` triggers a clean shutdown.
- `Ctrl+Q` is ignored on non-macOS systems to avoid unintended closures.
✅ Windows 11, built with MSVC  
✅ Cemu launches …

Disable Ctrl+Q shortcut on non-macOS platforms to prevent accidental exits during gameplay

---

src/Cafe/OS/libs/nsyshid/SkylanderXbox360.cpp

The important changes are [SkylanderXbox360.cpp:64](https://github.com/cemu-project/Cemu/commit/82808df91298c5b1c8bd296f09f757f93ed32497#diff-3de5948b6338ac177dbb8e904831e1995f001657c6fdac6e793ee146733a8f0eR64) and [SkylanderXbox360:73](https://github.com/cemu-project/Cemu/commit/82808df91298c5b1c8bd296f09f757f93ed32497#diff-3de5948b6338ac177dbb8e904831e1995f001657c6fdac6e793ee146733a8f0eR73)
Before, it was reallocating the `xboxAudioData` vector 16 times, now just allocating it with the final size once.
The rest of the changes here are code formatting and removal of unnecessary arguments.

nsyshid: Skylander Xbox 360 Portal small optimization and code formatting

---

src/gui/input/InputAPIAddWindow.cpp

The IP and port input boxes are not shown when the DSUController API is first selected when using wayland with kwin.
Setting the dialog as wxCAPTION causes kwin to add decorations to the window which for whatever reason causes the toplevel to resize correctly.
This may be a bug in wxWidgets or kwin.
With dialog style set to 0:
https://github.com/user-attachments/assets/42d15f24-f402-4217-bf85-594db658e063
With dialog style set to wxCAPTION:
https://github.com/user-attachments/assets/a05d0860-308d-4f31-9501-4df4f7f3bd77
Fixes #867

UI: wxCAPTION flag on input API dialog to fix kwin

---

src/Cemu/Logging/CemuLogging.cpp
src/config/LaunchSettings.cpp
src/config/LaunchSettings.h

I find the way Cemu logs intuitive.
When I try to track down an issue too much of my time is spent trying to figure out where my log lines are going.
What I want is to type `Cemu --help`, see that there's an option to print to stdout and use that.

"verbose" command line argument to log to stdout

---

src/gui/MainWindow.cpp
src/gui/components/wxGameList.cpp
src/gui/components/wxGameList.h

Various minor improvements to the macOS UI:
* Allow creating app shortcuts on Mac, similar to Linux and Windows
* Move the 'About' and 'General settings' menu items to where they would typically be found on Mac
* * Another copy of the existing 'General settings' menu item is still there in its original location
* Add `⌘,` keybinding for Settings, same as for other macOS apps
* Add MoltenVK to list of used libraries
Cemu menu:
App appearance in Launchpad:

Minor macOS UI improvements

---

src/Cafe/IOSU/legacy/iosu_boss.cpp

The Pretendo BOSS server does not accept HTTP/2 connections, even when the request is correctly formed (it assumes you're using a web browser). This, from what I've seen online, is not a problem because libcurl defaults to HTTP/1.1. Except on the Flatpak build for some reason. This fixes Splatoon for me.

boss: Use HTTP/1.1 instead of default

---

src/Cafe/GraphicPack/GraphicPack2.cpp
src/Cafe/GraphicPack/GraphicPack2.h

Allow graphic packs to overlay/redirect files into the code directory, using the `InternalVirtualCodeFolder` base path.

GraphicPack: Allow overlay for code folder

---

src/Cafe/IOSU/legacy/iosu_fpd.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_DownloadCommunityTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_UploadCommunityTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_UploadFavoriteTypes.cpp
src/Common/CafeString.h
src/util/helpers/StringHelpers.h

A recent version of Clang (actually libc++ 19 IIRC) has removed deprecated string templates. I replaced them with `std::vector`.

replace basic_string<> with std::vector because of new Clang

---

src/Cafe/HW/Latte/Core/LatteShaderCache.cpp
src/Cafe/OS/libs/nsyshid/Skylander.cpp
src/Cafe/OS/libs/snd_core/ax_out.cpp
src/audio/IAudioAPI.cpp
src/audio/IAudioAPI.h
src/config/CemuConfig.cpp
src/config/CemuConfig.h
src/gui/GeneralSettings2.cpp
src/gui/GeneralSettings2.h

In the Skylanders games, the portal that is currently emulated is the Trap Team portal. Normally it writes requests via the SetReport method, but the trap team portal also accepts audio requests via the Write method. The portal attached to the Trap Team portal is a Mono audio, 8000hz speaker, and audio requests are 64 bytes, which is 32 16 bit PCM audio samples.
I have also made the portal audio a setting similar to gamepad/tv audio, as well as changing some methods to allow for more than a binary choice when playing audio output.

nsyshid: Play Emulated Portal Audio via Mono Audio

---

src/gui/DownloadGraphicPacksWindow.cpp
src/gui/input/panels/InputPanel.cpp

I build the debug build with wxWidgets 3.3 on Windows. I fixed most of the asserts from wxWidgets.

UI: fix assertions

---

src/gui/wxgui/input/HotkeySettings.cpp
src/gui/wxgui/input/HotkeySettings.h

#1519 has problems with static initialization. It happens to work sometimes with some compilers, but my builds simply crash at start.
I fixed it by doing static initialization on demand.

UI: fix static initialization

---

src/gui/wxgui/AudioDebuggerWindow.cpp
src/gui/wxgui/GraphicPacksWindow2.cpp
src/gui/wxgui/GraphicPacksWindow2.h
src/gui/wxgui/components/wxGameList.cpp
src/gui/wxgui/debugger/ModuleWindow.cpp
src/gui/wxgui/input/HotkeySettings.cpp

This fixes some very minor issues:
- The placeholders for the game list icons are now black instead of white when using dark mode.
- If you disable an activated graphic pack it'll no longer change the text to black when using dark mode.
- Some other minor fixes for things that already seemed to work in dark mode.

UI: Fix minor dark mode issues

---

vcpkg.json

Fixes compilation failure on Linux with later libpipewire versions

build: Update vcpkg dependency SDL2 to 2.32.8

---

src/Cafe/HW/Espresso/Recompiler/IML/IMLRegisterAllocatorRanges.cpp
src/Cafe/HW/Latte/Renderer/Vulkan/VsyncDriver.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_InitializeTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_UploadCommunityTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_UploadFavoriteTypes.cpp
src/util/ChunkedHeap/ChunkedHeap.h

```
[build] [452/525] Building CXX object src/gui/wxgui/CMakeFiles/CemuWxGui.dir/GeneralSettings2.cpp.obj
[build] In file included from C:/src/Cemu/src/Cafe/HW/Latte/Renderer/Vulkan/LatteTextureVk.h:5,
[build]                  from C:/src/Cemu/src/Cafe/HW/Latte/Renderer/Vulkan/VulkanRenderer.h:6,
[build]                  from C:/src/Cemu/src/gui/wxgui/GeneralSettings2.cpp:30:
[build] C:/src/Cemu/src/util/ChunkedHeap/ChunkedHeap.h: In member function 'void ChunkedHeap<TMinimumAlignment>::verifyHeap()':
[build] C:/src/Cemu/src/util/ChunkedHeap/ChunkedHeap.h:286:49: warning: expected 'template' keyword before dependent template name [-Wmissing-template-keyword]
[build]   286 |                                         if (itr.offset < (dbgRange.offset + dbgRange.size) && (itr.offset + …
```

fix trivial compiler warnings

---

src/Cafe/OS/libs/nn_olv/nn_olv_DownloadCommunityTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_UploadCommunityTypes.cpp
src/Cafe/OS/libs/nn_olv/nn_olv_UploadFavoriteTypes.cpp

There is no functional change. `select_single_node` has been renamed to `select_node` and deprecated https://pugixml.org/docs/manual.html#v1.5.

fix pugixml deprecation warnings

---

.github/workflows/build.yml
.github/workflows/deploy_release.yml
README.md
src/resource/installer.nsi

Addition of an [NSIS](https://nsis.sourceforge.io/Main_Page) Windows installer to Cemu's build and distribution. Addresses #1491
Installers are more familiar to many Windows users and have the following benefits:
- Automatically creates shortcuts on the Desktop and in the Start Menu
- Appearance in Apps and Programs, and uninstallation through it
- Cleans registry leftovers
- User files in `AppData\Roaming` remain untouched
- Gives the application a dedicated default path in `AppData\Local`, rather than just leaving it float in Downloads or Documents, which is true for most users
- For inexperienced users, this can avoid problems caused by OneDrive syncing
- Automatically assigns Rom files (`.wud, .wux, .wua`) to be opened with Cemu
- Portable single-file installer for easy distribution …

Add NSIS Windows installer

---

src/input/api/Wiimote/WiimoteControllerProvider.cpp
src/input/api/Wiimote/WiimoteMessages.h

This is a fix for issue https://github.com/cemu-project/Cemu/issues/1664
This code is straight from the referenced issue. It adds handling of the [inactive MotionPlus extension events](https://github.com/supertuxkart/stk-code/blob/d4be5d133893f8a871c318d355f6e051fca38091/lib/wiiuse/src/wiiuse_internal.h#L230) which cause Wii Remote Plus controllers to constantly disconnect and reconnect.
I ran into this bug, found the issue and saw that @capitalistspz had requested a pull request. So I've done so.

Add support for Wii Remote Plus by handling the inactive MotionPlus extension events

---

src/gui/wxgui/components/wxGameList.cpp
src/gui/wxgui/components/wxGameList.h

When you switch the game list from list view to icon view and back again, it forgets which column was sorted. I fixed it.

UI: fix sorting after style switch
